<?
$aMenuLinks = Array(
	Array(
		"Каталог", 
		"/catalog/", 
		Array(), 
		Array("ICON"=>"icon_mobile_menu_bottom_catalog"), 
		"" 
	),
	Array(
		"Услуги", 
		"/services/", 
		Array(), 
		Array("ICON"=>"icon_service"), 
		"" 
	),
	Array(
		"Акции", 
		"/promotions/", 
		Array(), 
		Array("ICON"=>"icon_menu_new_sale"), 
		"" 
	),
	Array(
		"Бренды", 
		"/brands/", 
		Array(), 
		Array("ICON"=>"icon_menu_new_brands"), 
		"" 
	),
	Array(
		"Новости", 
		"/news/", 
		Array(), 
		Array("ICON"=>"icon_mobile_menu_bottom_news"), 
		"" 
	),
	Array(
		"Блог", 
		"/blog/", 
		Array(), 
		Array("ICON"=>"icon_menu_new_blog"), 
		"" 
	),
	Array(
		"Помощь", 
		"/help/", 
		Array(), 
		Array("ICON"=>"icon_mobile_menu_bottom_help"), 
		"" 
	),
	Array(
		"Контакты", 
		"/about/contacts/", 
		Array(), 
		Array("ICON"=>"icon_mobile_menu_bottom_contacts"), 
		"" 
	),
	Array(
		"FAQ", 
		"/questions/", 
		Array(), 
		Array("ICON"=>"icon_faq"), 
		"" 
	),
	Array(
		"Влог", 
		"/vlog/", 
		Array(), 
		Array("ICON"=>"icon_video-player"), 
		"" 
	)
);

if(IsModuleInstalled('kit.b2bshop') && (file_exists($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/kit.b2bshop/") || file_exists($_SERVER["DOCUMENT_ROOT"]."/bitrix/wizards/kit/b2bshop/"))) {
    $aMenuLinks[] = array(
        "B2bCabinet",
        "/b2bcabinet",
        Array(),
        Array("ICON"=>"icon_b2bcabinet"),
        ""
    );
}
?>