<?php if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) die();

/**
 * @var CMain $APPLICATION
 * @var CBitrixComponent $component
 * @var array $arResult
 * @var array $arParams
 */

?>
<?php $APPLICATION->IncludeComponent(
    'bitrix:news.detail',
    '.default',
    array(
        "COMPONENT_TEMPLATE" => ".default",
        "IBLOCK_TYPE" => $arParams['IBLOCK_TYPE'],
        "IBLOCK_ID" => $arParams['IBLOCK_ID'],
        "ELEMENT_ID" => $arResult['VARIABLES']['ELEMENT_ID'],
        "ELEMENT_CODE" => $arResult['VARIABLES']['ELEMENT_CODE'],
        "CHECK_DATES" => $arParams['CHECK_DATES'],
        'FIELD_CODE' => $arParams['DETAIL_FIELD_CODE'],
        'PROPERTY_CODE' => $arParams['DETAIL_PROPERTY_CODE'],
        "IBLOCK_URL" => $arResult['FOLDER'].$arResult['URL_TEMPLATES']['news'],
        "DETAIL_URL" => $arResult['FOLDER'].$arResult['URL_TEMPLATES']['section'],
        "CACHE_TYPE" => $arParams["CACHE_TYPE"],
        "CACHE_TIME" => $arParams["CACHE_TIME"],
        "CACHE_GROUPS" => $arParams["CACHE_GROUPS"],
        "SET_TITLE" => $arParams['SET_TITLE'],
        "SET_CANONICAL_URL" => $arParams['DETAIL_SET_CANONICAL_URL'],
        "SET_BROWSER_TITLE" => $arParams['SET_BROWSER_TITLE'],
        "BROWSER_TITLE" => $arParams['BROWSER_TITLE'],
        "SET_META_KEYWORDS" => $arParams['SET_META_KEYWORDS'],
        "META_KEYWORDS" => $arParams['META_KEYWORDS'],
        "SET_META_DESCRIPTION" => $arParams['SET_META_DESCRIPTION'],
        "META_DESCRIPTION" => $arParams['META_DESCRIPTION'],
        "SET_LAST_MODIFIED" => "N",
        "INCLUDE_IBLOCK_INTO_CHAIN" => $arParams['INCLUDE_IBLOCK_INTO_CHAIN'],
        "ADD_SECTIONS_CHAIN" => $arParams['ADD_SECTIONS_CHAIN'],
        "ADD_ELEMENT_CHAIN" => $arParams['ADD_ELEMENT_CHAIN'],
        "ACTIVE_DATE_FORMAT" => $arParams['DETAIL_ACTIVE_DATE_FORMAT'],
        "USE_PERMISSIONS" => $arParams['USE_PERMISSIONS'],
        "STRICT_SECTION_CHECK" => "N",
        "DISPLAY_DATE" => "N",
        "DISPLAY_NAME" => "N",
        "DISPLAY_PICTURE" => "N",
        "DISPLAY_PREVIEW_TEXT" => "N",
        "USE_SHARE" => "N",
        "PAGER_TEMPLATE" => ".default",
        "DISPLAY_TOP_PAGER" => "N",
        "DISPLAY_BOTTOM_PAGER" => "N",
        "PAGER_TITLE" => "",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "SET_STATUS_404" => $arParams["SET_STATUS_404"],
        "SHOW_404" => $arParams["SHOW_404"],
        "MESSAGE_404" => $arParams["MESSAGE_404"],
        'PROPERTY_BANNER_TYPE' => $arParams['DETAIL_PROPERTY_BANNER_TYPE'],
        'PROPERTY_BANNER_URL' => $arParams['DETAIL_PROPERTY_BANNER_URL'],
        'PROPERTY_BANNER_IMAGE' => $arParams['DETAIL_PROPERTY_BANNER_IMAGE'],
        'PROPERTY_CHARACTERISTICS' => $arParams['DETAIL_PROPERTY_CHARACTERISTICS'],
        'PROPERTY_INFORMATION' => $arParams['DETAIL_PROPERTY_INFORMATION'],
        'PROPERTY_FEATURES' => $arParams['DETAIL_PROPERTY_FEATURES'],
        'PROPERTY_EXAMPLE' => $arParams['DETAIL_PROPERTY_EXAMPLE'],
        'PROPERTY_RESULT' => $arParams['DETAIL_PROPERTY_RESULT'],
        'PROPERTY_REVIEW' => $arParams['DETAIL_PROPERTY_REVIEW'],
        'PROPERTY_SERVICES' => $arParams['DETAIL_PROPERTY_SERVICES'],
        'SERVICES_PROPERTY_LINK' => $arParams['DETAIL_SERVICES_PROPERTY_LINK'],
        'SERVICES_IBLOCK_TYPE' => $arParams['DETAIL_SERVICES_IBLOCK_TYPE'],
        'SERVICES_IBLOCK_ID' => $arParams['DETAIL_SERVICES_IBLOCK_ID'],
        'PROPERTY_PROJECTS' => $arParams['DETAIL_PROPERTY_PROJECTS'],
        'BANNER_SHOW' => $arParams['DETAIL_BANNER_SHOW'],
        'BANNER_HEIGHT' => $arParams['DETAIL_BANNER_HEIGHT'],
        'BANNER_TYPE' => $arParams['DETAIL_BANNER_TYPE'],
        'BANNER_URL' => $arParams['DETAIL_BANNER_URL'],
        'BANNER_BUTTON' => $arParams['DETAIL_BANNER_BUTTON'],
        'BANNER_IMAGE' => $arParams['DETAIL_BANNER_IMAGE'],

        'CHARACTERISTICS_SHOW' => $arParams['DETAIL_CHARACTERISTICS_SHOW'],
        'CHARACTERISTICS_COLUMNS' => $arParams['DETAIL_CHARACTERISTICS_COLUMNS'],
        'INFORMATION_SHOW' => $arParams['DETAIL_INFORMATION_SHOW'],
        'INFORMATION_COLUMNS' => $arParams['DETAIL_INFORMATION_COLUMNS'],
        'FEATURES_SHOW' => $arParams['DETAIL_FEATURES_SHOW'],
        'FEATURES_NARROW' => $arParams['DETAIL_FEATURES_NARROW'],
        'EXAMPLE_SHOW' => $arParams['DETAIL_EXAMPLE_SHOW'],
        'EXAMPLE_SHADOW' => $arParams['DETAIL_EXAMPLE_SHADOW'],
        'RESULT_SHOW' => $arParams['DETAIL_RESULT_SHOW'],
        'RESULT_NARROW' => $arParams['DETAIL_RESULT_NARROW'],
        'RESULT_BACKGROUND' => $arParams['DETAIL_RESULT_BACKGROUND'],
        'REVIEW_SHOW' => $arParams['DETAIL_REVIEW_SHOW'],
        'REVIEW_NARROW' => $arParams['DETAIL_REVIEW_NARROW'],
        'SERVICES_SHOW' => $arParams['DETAIL_SERVICES_SHOW'],
        'PROJECTS_SHOW' => $arParams['DETAIL_PROJECTS_SHOW']
    ),
    $component
); ?>
