п»ї/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","az",{euro:"Avropa valyuta iЕџarЙ™si",lsquo:"Sol tЙ™k dД±rnaq iЕџarЙ™si",rsquo:"SaДџ tЙ™k dД±rnaq iЕџarЙ™si",ldquo:"Sol cГјt dД±rnaq iЕџarЙ™si",rdquo:"SaДџ cГјt dД±rnaq iЕџarЙ™si",ndash:"Г‡Д±xma iЕџarЙ™si",mdash:"Tire",iexcl:"Г‡evrilmiЕџ nida iЕџarЙ™si",cent:"Sent iЕџarЙ™si",pound:"Funt sterlinq iЕџarЙ™si",curren:"Valyuta iЕџarЙ™si",yen:"Д°ena iЕџarЙ™si",brvbar:"SД±nmД±Еџ zolaq",sect:"Paraqraf iЕџarЙ™si",uml:"Umlyaut",copy:"MГјЙ™llif hГјquqlarД± haqqД±nda iЕџarЙ™si",ordf:"QadД±n sД±ra indikatoru (a)",laquo:"Sola gГ¶stЙ™rЙ™n cГјt bucaqlД± dД±rnaq",
not:"QEYRД° iЕџarЙ™si",reg:"Qeyd olunmuЕџ iЕџarЙ™si",macr:"Makron",deg:"DЙ™rЙ™cЙ™ iЕџarЙ™si",sup2:"YuxarД± indeks 2",sup3:"YuxarД± indeks 3",acute:"VurДџu iЕџarЙ™si",micro:"Mikro iЕџarЙ™si",para:"Abzas iЕџarЙ™si",middot:"Orta nГ¶qtЙ™",cedil:"Tsedilla iЕџarЙ™si",sup1:"YuxarД± indeks 1",ordm:"KiЕџi say indikatoru (o)",raquo:"SaДџa gГ¶stЙ™rЙ™n cГјt bucaqlД± dД±rnaq",frac14:"DГ¶rddЙ™ bir hissЙ™ kЙ™sri",frac12:"Bir yarД±m kЙ™sri",frac34:"DГ¶rddЙ™ ГјГ§ hissЙ™ kЙ™sri",iquest:"Г‡evrilmiЕџ sual iЕџarЙ™si",Agrave:"Soldan vurДџu ilЙ™ A",Aacute:"VurДџu ilЙ™ A",
Acirc:"Dam iЕџarЙ™si ilЙ™ A",Atilde:"Tilda iЕџarЙ™si ilЙ™ A",Auml:"Umlyaut ilЙ™ A",Aring:"DairЙ™li A",AElig:"Г† hЙ™rfi",Ccedil:"Tsedilla ilЙ™ C",Egrave:"Soldan vurДџu ilЙ™ E",Eacute:"VurДџu ilЙ™ E",Ecirc:"Dam iЕџarЙ™si ilЙ™ E",Euml:"Umlyaut ilЙ™ E",Igrave:"Soldan vurДџu ilЙ™ I",Iacute:"VurДџu ilЙ™ I",Icirc:"Dam iЕџarЙ™si ilЙ™ I",Iuml:"Umlyaut ilЙ™ I",ETH:"Eth latin hЙ™rfi",Ntilde:"Tilda iЕџarЙ™si ilЙ™ N",Ograve:"Soldan vurДџu ilЙ™ O",Oacute:"VurДџu ilЙ™ O",Ocirc:"Dam iЕџarЙ™si ilЙ™ E",Otilde:"Tilda iЕџarЙ™si ilЙ™ O",Ouml:"Umlyaut ilЙ™ O",
times:"Vurma iЕџarЙ™si",Oslash:"ГњstxЙ™ttli O",Ugrave:"Soldan vurДџu ilЙ™ U",Uacute:"VurДџu ilЙ™ U",Ucirc:"Dam iЕџarЙ™si ilЙ™ U",Uuml:"Umlyaut ilЙ™ U",Yacute:"VurДџu ilЙ™ Y",THORN:"Thorn hЙ™rfi",szlig:"Д°ti s kiГ§ik hЙ™rfi",agrave:"Soldan vurДџu ilЙ™ a",aacute:"VurДџu ilЙ™ a",acirc:"Dam iЕџarЙ™si ilЙ™ a",atilde:"Tilda iЕџarЙ™si ilЙ™ a",auml:"Umlyaut ilЙ™ a",aring:"DairЙ™li a",aelig:"Г¦ hЙ™rfi",ccedil:"Г§ hЙ™rfi",egrave:"Soldan vurДџu ilЙ™ e",eacute:"VurДџu ilЙ™ e",ecirc:"Dam iЕџarЙ™si ilЙ™ e",euml:"Umlyaut ilЙ™ e",igrave:"Soldan vurДџu ilЙ™ i",
iacute:"VurДџu ilЙ™ i",icirc:"Dam iЕџarЙ™si ilЙ™ i",iuml:"Umlyaut ilЙ™ i",eth:"eth kiГ§ik hЙ™rfi",ntilde:"Tilda iЕџarЙ™si ilЙ™ n",ograve:"Soldan vurДџu ilЙ™ o",oacute:"VurДџu ilЙ™ o",ocirc:"Dam iЕџarЙ™si ilЙ™ o",otilde:"Tilda iЕџarЙ™si ilЙ™ o",ouml:"Umlyaut ilЙ™ o",divide:"BГ¶lГјnmЙ™ iЕџarЙ™si",oslash:"ГњstxЙ™ttli o",ugrave:"Soldan vurДџu ilЙ™ u",uacute:"VurДџu ilЙ™ u",ucirc:"Dam iЕџarЙ™si ilЙ™ u",uuml:"Umlyaut ilЙ™ u",yacute:"VurДџu ilЙ™ y",thorn:"Thorn kiГ§ik hЙ™rfi",yuml:"Umlyaut ilЙ™ y",OElig:"OE ligaturasД±",oelig:"oe ligaturasД±",372:"Dam iЕџarЙ™si ilЙ™ W",
374:"Dam iЕџarЙ™si ilЙ™ Y",373:"Dam iЕџarЙ™si ilЙ™ w",375:"Dam iЕџarЙ™si ilЙ™ y",sbquo:"AЕџaДџД± dД±rnaq",8219:"TЙ™k yuxarД± Г§evrilmiЕџ dД±rnaq",bdquo:"AЕџaДџД± cГјtlГј dД±rnaqlar",hellip:"ГњfГјqi ellips",trade:"ЖЏmtЙ™Й™ niЕџanД±",9658:"SaДџa gГ¶stЙ™rici",bull:"Marker",rarr:"SaДџa istiqamЙ™tlЙ™ndirЙ™n ox",rArr:"SaДџa istiqamЙ™tlЙ™ndirЙ™n cГјtlГј ox",hArr:"HЙ™rtЙ™rЙ™fli ox",diams:"Qara kЙ™rpic",asymp:"TЙ™xmini barabЙ™r"});