п»ї/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","es-mx",{euro:"Signo de Euro",lsquo:"Comillas simple izquierda",rsquo:"Comillas simple derecha",ldquo:"Comillas dobles izquierda",rdquo:"Comillas dobles derecha",ndash:"GuiГіn corto",mdash:"GuiГіn largo",iexcl:"Signo de exclamaciГіn invertido",cent:"Signo de centavo",pound:"Signo de Libra",curren:"Signo de moneda",yen:"Signo de Yen",brvbar:"Barra rota",sect:"Signo de la secciГіn",uml:"DiГ©resis",copy:"Signo de Derechos reservados",ordf:"Indicador ordinal femenino",
laquo:"SeГ±al de doble ГЎngulo hacia la izquierda",not:"Sin signo",reg:"Signo registrado",macr:"Macron",deg:"signo de grados",sup2:"SuperГ­ndice dos",sup3:"SuperГ­ndice tres",acute:"Acento agudo",micro:"Signo micro",para:"Signo pilcrow",middot:"Punto medio",cedil:"Cedilla",sup1:"SuperГ­ndice uno",ordm:"Indicador ordinal masculino",raquo:"SeГ±al de doble ГЎngulo hacia la derecha",frac14:"FracciГіn un cuarto",frac12:"FracciГіn medio",frac34:"FracciГіn tres cuartos",iquest:"Signo de interrogaciГіn invertido",Agrave:"Letra mayГєscula latina A con acento grave",
Aacute:"Letra mayГєscula latina A con acento agudo",Acirc:"Letra mayГєscula latina A con circunflexo",Atilde:"Letra mayГєscula latina A con tilde",Auml:"Letra mayГєscula latina A con diГ©resis",Aring:"Letra mayГєscula latina A con anillo arriba",AElig:"Letra mayГєscula latina Г†",Ccedil:"Letra mayГєscula latina C con cedilla",Egrave:"Letra mayГєscula latina E con acento grave",Eacute:"Letra mayГєscula latina E con acento agudo",Ecirc:"Letra mayГєscula latina E con circumflex",Euml:"Letra mayГєscula latina E con diГ©resis",
Igrave:"Letra mayГєscula latina I con acento grave",Iacute:"Letra mayГєscula latina I con acento agudo",Icirc:"Letra mayГєscula latina I con circumflex",Iuml:"Letra mayГєscula latina E con diГ©resis",ETH:"Letra mayГєscula latina Eth",Ntilde:"Letra mayГєscula latina N con tilde",Ograve:"Letra mayГєscula latina O con acento grave",Oacute:"Letra mayГєscula latina O con acento agudo",Ocirc:"Letra mayГєscula latina O con circumflex",Otilde:"Letra mayГєscula latina O con tilde",Ouml:"Letra mayГєscula latina O con diГ©resis",
times:"Signo de multiplicaciГіn",Oslash:"Letra mayГєscula latina O con trazo",Ugrave:"Letra mayГєscula latina U con acento grave",Uacute:"Letra mayГєscula latina U con acento agudo",Ucirc:"Letra mayГєscula latina U con circumflex",Uuml:"Letra mayГєscula latina U con diГ©resis",Yacute:"Letra mayГєscula latina Y con acento agudo",THORN:"Letra mayГєscula latina Thorn",szlig:"Letra pequeГ±a latina s",agrave:"Letra pequeГ±a latina a con acento grave",aacute:"Letra pequeГ±a latina a con acento agudo",acirc:"Letra pequeГ±a latina a con circumflex",
atilde:"Letra pequeГ±a latina a con tilde",auml:"Letra pequeГ±a latina a con diГ©resis",aring:"Letra pequeГ±a latina a con anillo arriba",aelig:"Letra pequeГ±a latina Г¦",ccedil:"Letra pequeГ±a latina c con cedilla",egrave:"Letra pequeГ±a latina e con acento grave",eacute:"Letra pequeГ±a latina e con acento agudo",ecirc:"Letra pequeГ±a latina e con circumflex",euml:"Letra pequeГ±a latina e con diГ©resis",igrave:"Letra pequeГ±a latina i con acento grave",iacute:"Letra pequeГ±a latina i con acento agudo",icirc:"Letra pequeГ±a latina i con circumflex",
iuml:"Letra pequeГ±a latina i con diГ©resis",eth:"Letra pequeГ±a latina eth",ntilde:"Letra pequeГ±a latina n con tilde",ograve:"Letra pequeГ±a latina o con acento grave",oacute:"Letra pequeГ±a latina o con acento agudo",ocirc:"Letra pequeГ±a latina o con circumflex",otilde:"Letra pequeГ±a latina o con tilde",ouml:"Letra pequeГ±a latina o con diГ©resis",divide:"Signo de divisiГіn",oslash:"Letra pequeГ±a latina o con trazo",ugrave:"Letra pequeГ±a latina u con acento grave",uacute:"Letra pequeГ±a latina u con acento agudo",
ucirc:"Letra pequeГ±a latina u con circumflex",uuml:"Letra pequeГ±a latina u con diГ©resis",yacute:"Letra pequeГ±a latina y con acento agudo",thorn:"Espina de letra pequeГ±a latina",yuml:"Letra pequeГ±a latina y con diГ©resis",OElig:"Ligadura de capital latino OE",oelig:"Ligadura de pequeГ±a latino OE",372:"Letra latina mayГєscula W con circunflexo",374:"Letra latina mayГєscula Y con circunflexo",373:"Letra latina minГєscula w con circunflexo",375:"Letra latina minГєscula y con circunflexo",sbquo:"Signo de comillas simple abajo",
8219:"Signo de comillas simple arriba",bdquo:"Signo de doble comillas abajo",hellip:"Elipsis horizontal",trade:"Signo merccantl",9658:"Puntero derecho negro",bull:"Bala",rarr:"Flecha hacia la derecha",rArr:"Doble flecha hacia la derecha",hArr:"Flecha doble izquierda derecha",diams:"Palo de diamante negro",asymp:"Casi igual a"});