п»ї/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","hr",{euro:"Euro znak",lsquo:"Lijevi jednostruki navodnik",rsquo:"Desni jednostruki navodnik",ldquo:"Lijevi dvostruki navodnik",rdquo:"Desni dvostruki navodnik",ndash:"En crtica",mdash:"Em crtica",iexcl:"Naopaki uskliДЌnik",cent:"Cent znak",pound:"Funta znak",curren:"Znak valute",yen:"Yen znak",brvbar:"Potrgana preДЌka",sect:"Znak odjeljka",uml:"Prijeglasi",copy:"Copyright znak",ordf:"ЕЅenska redna oznaka",laquo:"Lijevi dvostruki uglati navodnik",not:"Not znak",
reg:"Registered znak",macr:"Crta iznad",deg:"Stupanj znak",sup2:"Eksponent 2",sup3:"Eksponent tri",acute:"Akcent",micro:"Mikro znak",para:"Znak paragrafa",middot:"Srednja toДЌka",cedil:"Cedilla",sup1:"Eksponent 1",ordm:"MuЕЎka redna oznaka",raquo:"Desni dvostruku uglati navodnik",frac14:"ДЊetvrtina",frac12:"Polovina",frac34:"Tri ДЌetvrtine",iquest:"Naopaki upitnik",Agrave:"Veliko latinsko slovo A s akcentom",Aacute:"LatiniДЌno veliko slovo A sa oЕЎtrim naglaskom",Acirc:"LatiniДЌno veliko slovo A sa circumflex",
Atilde:"LatiniДЌno veliko slovo A sa tildom",Auml:"LatiniДЌno veliko slovo A sa diaeresis",Aring:"LatiniДЌno veliko slovo A sa gornjim prstenom",AElig:"LatiniДЌno veliko slovo Г†",Ccedil:"Veliko latiniДЌno slovo C sa cedilla",Egrave:"Veliko latiniДЌno slovo E sa akcentom",Eacute:"Veliko latiniДЌno slovo E sa  akcentom",Ecirc:"Veliko latiniДЌno slovo E sa circumflex",Euml:"Veliko latiniДЌno slovo E sa diaresis",Igrave:"Veliko latiniДЌno slovo I sa akcentom",Iacute:"Veliko latiniДЌno slovo I sa akcentom",Icirc:"Veliko latiniДЌno slovo I sa circumflex",
Iuml:"Veliko latiniДЌno slovo I sa diaresis",ETH:"Veliko latiniДЌno slovo Eth",Ntilde:"Veliko latiniДЌno slovo N sa tildom",Ograve:"Veliko latiniДЌno slovo O sa akcentom",Oacute:"Veliko latiniДЌno slovo O sa akcentom",Ocirc:"Veliko latiniДЌno slovo O sa circumflex",Otilde:"Veliko latiniДЌno slovo O sa tildom",Ouml:"Veliko latiniДЌno slovo O sa diaresis",times:"Znak mnoЕѕenja",Oslash:"Veliko latiniДЌno slovo O sa crtom",Ugrave:"Veliko latiniДЌno slovo U sa akcentom",Uacute:"Veliko latiniДЌno slovo U sa akcentom",
Ucirc:"Veliko latiniДЌno slovo U sa circumflex",Uuml:"Veliko latiniДЌno slovo U sa diaresis",Yacute:"Veliko latiniДЌno slovo Y sa akcentom",THORN:"Veliko latiniДЌno slovo Trn",szlig:"Malo latiniДЌno slovo oЕЎtro s",agrave:"Malo latiniДЌno slovo a sa akcentom",aacute:"Malo latiniДЌno slovo sa akcentom",acirc:"Malo latiniДЌno slovo a sa circumflex",atilde:"Malo latiniДЌno slovo a sa tildom",auml:"Malo latiniДЌno slovo a sa diaresis",aring:"Malo latiniДЌno slovo a sa gornjim prstenom",aelig:"Malo latiniДЌno slovo Г¦",
ccedil:"Malo latiniДЌno slovo e sa cedilla",egrave:"Malo latiniДЌno slovo e sa akcentom",eacute:"Malo latiniДЌno slovo e sa akcentom",ecirc:"Malo latiniДЌno slovo e sa circumflex",euml:"Malo latiniДЌno slovo e sa diaresis",igrave:"Malo latiniДЌno slovo i sa akcentom",iacute:"Malo latiniДЌno slovo i sa akcentom",icirc:"Malo latiniДЌno slovo i sa circumflex",iuml:"Malo latiniДЌno slovo i sa diaresis",eth:"Malo latiniДЌno slovo eth",ntilde:"Malo latiniДЌno slovo n sa tildom",ograve:"Malo latiniДЌno slovo o sa akcentom",
oacute:"Malo latiniДЌno slovo o sa akcentom",ocirc:"Malo latiniДЌno slovo o sa circumflex",otilde:"Malo latiniДЌno slovo o sa tildom",ouml:"Malo latiniДЌno slovo o sa diaresis",divide:"Znak dijeljenja",oslash:"Malo latiniДЌno slovo o sa crtom",ugrave:"Malo latiniДЌno slovo s akcentom",uacute:"Malo latiniДЌno slovo u sa akcentom",ucirc:"Malo latiniДЌno slovo sa circumflex",uuml:"Malo latiniДЌno slovo u sa diaresis",yacute:"Malo latiniДЌno slovo y s akcentom",thorn:"Malo latiniДЌno slovo Trn",yuml:"Malo latiniДЌno slovo y sa diaresis",
OElig:"Veliko latiniДЌno slovo OE",oelig:"Malo latiniДЌno slovoe OE",372:"Veliko latiniДЌno slovo W sa circumflex",374:"Veliko latiniДЌno slovo Y sa circumflex",373:"Malo latiniДЌno slovo w sa circumflex",375:"Malo latiniДЌno slovo y sa circumflex",sbquo:"Jednostruki donji navodnik",8219:"Jednostruki gornji navodnik",bdquo:"Dvostruki donji navodnik",hellip:"Tri toДЌkice",trade:"TM znak",9658:"Crni desni pokazivaДЌ",bull:"Bullet",rarr:"Desna strelica",rArr:"Desna dvostruka strelica",hArr:"Dvostruka strelica",
diams:"Crni dijamant",asymp:"PribliЕѕno"});