<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php") ?>
<?php

$APPLICATION->SetTitle("Контакты");

?>
<?php $APPLICATION->IncludeComponent(
	"bitrix:news.list", 
	"contacts", 
	array(
		"IBLOCK_TYPE" => "#CONTENT_CONTACTS_IBLOCK_TYPE#",
		"IBLOCK_ID" => "#CONTENT_CONTACTS_IBLOCK_ID#",
		"NEWS_COUNT" => "20",
		"SETTINGS_USE" => "Y",
		"REGIONALITY_USE" => "N",
		"REGIONALITY_PROPERTY" => "REGIONS",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"FILTER_NAME" => "",
		"FIELD_CODE" => array(),
		"PROPERTY_CODE" => array(
			"MAP",
			"CITY",
			"ADDRESS",
			"PHONE",
			"EMAIL",
			"WORK_TIME"
		),
		"CHECK_DATES" => "N",
		"MAP_VENDOR" => "google",
		"CONTACT_ID" => "",
		"PROPERTY_MAP" => "MAP",
		"API_KEY_MAP" => "",
		"PROPERTY_STORE_ID" => "STORE_ID",
		"PROPERTY_CITY" => "CITY",
		"PROPERTY_ADDRESS" => "ADDRESS",
		"PROPERTY_PHONE" => "PHONE",
		"PROPERTY_EMAIL" => "EMAIL",
		"PROPERTY_WORK_TIME" => "WORK_TIME",
		"PROPERTY_OPENING_HOURS" => "OPENING_HOURS",
		"WEB_FORM_ID" => "#FORMS_FEEDBACK_ID#",
		"WEB_FORM_CONSENT_URL" => "#SITE_DIR#company/consent/",
		"SHOW_MAP" => "Y",
		"SHOW_FORM" => "Y",
		"SHOW_LIST" => "NONE",
		"TITLE_SHOW" => "Y",
		"TITLE_TEXT" => "",
		"DESCRIPTION_SHOW" => "Y",
		"DESCRIPTION_TEXT" => "",
		"DETAIL_URL" => "#SITE_DIR#contacts/stores/#ID#/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"CACHE_TYPE" => "N",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"SET_TITLE" => "Y",
		"SET_BROWSER_TITLE" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_META_DESCRIPTION" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"STRICT_SECTION_CHECK" => "N",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_TITLE" => "Контакты",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SET_STATUS_404" => "Y",
		"SHOW_404" => "Y",
		"FILE_404" => "#SITE_DIR#404.php"
	),
	false
); ?>
<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php") ?>
