п»ї/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","az",{title:"ЖЏlillЙ™rЙ™ dЙ™stЙ™k ГјzrЙ™ tЙ™limat",contents:"KГ¶mЙ™k. PЙ™ncЙ™rЙ™ni baДџlamaq ГјГ§Гјn ESC basД±n.",legend:[{name:"ЖЏsas",items:[{name:"DГјzЙ™liЕџ edЙ™nin alЙ™tlЙ™r Г§ubuДџu",legend:"PanelЙ™ keГ§mЙ™k ГјГ§Гјn ${toolbarFocus} basД±n. NГ¶vbЙ™ti panelЙ™ TAB, Й™vvЙ™lki panelЙ™ isЙ™ SHIFT+TAB dГјymЙ™si vasitЙ™si ilЙ™ keГ§Й™ bilЙ™rsiz. PaneldЙ™ki dГјymЙ™lЙ™r arasД±nda sol vЙ™ saДџ ox dГјymЙ™si ilЙ™ keГ§id edЙ™ bilЙ™rsiz. SeГ§ilmiЕџ dГјymЙ™si SPACE vЙ™ ya ENTER ilЙ™ iЕџlЙ™dЙ™ bilЙ™rsiniz."},{name:"Redaktorun pЙ™ncЙ™rЙ™si",legend:"PЙ™ncЙ™rЙ™ iГ§indЙ™ nГ¶vbЙ™ti element seГ§mЙ™k ГјГ§Гјn TAB dГјymЙ™ni basД±n, Й™vvЙ™lki isЙ™ - SHIFT+TAB. TЙ™sdiq edilmЙ™si ГјГ§Гјn ENTER, imtina edilmЙ™si isЙ™ ESC diymЙ™lЙ™ri istifadЙ™ edin. PЙ™ncЙ™rЙ™dЙ™ bir neГ§Й™ vЙ™rЙ™q olanda olnarД±n siyahД± ALT+F10 ilЙ™ aГ§a bilЙ™rsiz. VЙ™rЙ™qlЙ™rin siyahД± fokus altД±nda olanda ox dГјymЙ™lЙ™r vasitЙ™si ilЙ™ onlarД±n arasД±nda keГ§id edЙ™ bilЙ™rsiz."},
{name:"Redaktorun seГ§imlЙ™rin menyusu",legend:"SeГ§imlЙ™ri redaktЙ™ etmЙ™k ГјГ§Гјn ${contextMenu} ya da APPLICATION KEY basД±n. NГ¶vbЙ™ti seГ§imЙ™ keГ§mЙ™k ГјГ§Гјn TAB ya AЕћAДћI OX dГјymЙ™sini basД±n, Й™vvЙ™lki isЙ™ - SHIFT+TAB ya YUXARI OX. SeГ§imi arД±maq SPACE ya ENTER dГјymЙ™lЙ™ri istifadЙ™ edin. Alt menyunu aГ§maq ГјГ§Гјn SPACE, ENTER ya SAДћA OX basД±n. ESC ya SOLA OX ilЙ™ geriyЙ™ qayД±da bilЙ™rsiz. BГјtГјn menyunu ESC ilЙ™ baДџlД±yД±n."},{name:"DГјzЙ™liЕџ edЙ™nin siyahД± qutusu",legend:"SiyahД± qutusu iГ§indЙ™ nГ¶vbЙ™ti bЙ™nd seГ§mЙ™k ГјГ§Гјn TAB ya AЕћAДћI OX, Й™vvЙ™lki isЙ™ SHIFT+TAB ya YUXARI OX basД±n. SeГ§imi arД±maq SPACE ya ENTER dГјymЙ™lЙ™ri istifadЙ™ edin. SiyahД± qutusu ESC ilЙ™ baДџlД±yД±n."},
{name:"Redaktor elementin cД±ДџД±r paneli",legend:"Elementin cД±ДџД±r paneli seГ§mЙ™k ГјГ§Гјn ${elementsPathFocus} basД±n. NГ¶vbЙ™ti element seГ§mЙ™k ГјГ§Гјn TAB ya SAДћA OX, Й™vvЙ™lki isЙ™ SHIFT+TAB ya SOLA OX istifadЙ™ edin. Elementi arД±maq SPACE ya ENTER dГјymЙ™lЙ™ri mГ¶vcuddur."}]},{name:"ЖЏmrlЙ™r",items:[{name:"ЖЏmri geri qaytar",legend:"${undo} basД±n"},{name:"Geri Й™mri",legend:"${redo} basД±n"},{name:"QalД±n Й™mri",legend:"${bold}  basД±n"},{name:"Kursiv Й™mri",legend:"${italic} basД±n"},{name:"Altdan xЙ™tt Й™mri",legend:"${underline} basД±n"},
{name:"Link Й™mri",legend:"${link} basД±n"},{name:"Paneli gizlЙ™t Й™mri",legend:"${toolbarCollapse} basД±n"},{name:"ЖЏvvЙ™lki fokus sahЙ™si seГ§ Й™mrД±",legend:"Kursordan Й™vvЙ™l Й™n yaxД±n Й™lГ§atmaz yerЙ™ dЙ™ymЙ™k ГјГ§Гјn ${accessPreviousSpace} basД±n, misal ГјГ§Гјn: iki dal-badal HR teg. Uzaq yerlЙ™rЙ™ dЙ™ymЙ™k ГјГ§Гјn bir neГ§Й™ dЙ™fЙ™ basД±n."},{name:"NГ¶vbЙ™ti fokus sahЙ™si seГ§ Й™mrД±",legend:"Kursordan sonra Й™n yaxД±n Й™lГ§atmaz yerЙ™ dЙ™ymЙ™k ГјГ§Гјn ${accessNextSpace} basД±n, misal ГјГ§Гјn: iki dal-badal HR teg. Uzaq yerlЙ™rЙ™ dЙ™ymЙ™k ГјГ§Гјn bir neГ§Й™ dЙ™fЙ™ basД±n."},
{name:"HЙ™rtЙ™rЙ™fli KГ¶mЙ™k",legend:"${a11yHelp} basД±n"},{name:" Paste as plain text",legend:"Press ${pastetext}",legendEdge:"Press ${pastetext}, followed by ${paste}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Sola ox iЕџarЙ™si",upArrow:"YuxarД± ox iЕџarЙ™si",rightArrow:"SaДџa ox iЕџarЙ™si",downArrow:"AЕџaДџД± ox iЕџarЙ™si",insert:"Insert",leftWindowKey:"Soldaki Windows dГјymЙ™si",rightWindowKey:"SaДџdaki Windows dГјymЙ™si",selectKey:"DГјymЙ™ni seГ§in",
numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Vurma",add:"ЖЏlavЙ™ et",subtract:"Г‡Д±xma",decimalPoint:"Onluq kЙ™sri tam Й™dЙ™ddЙ™n ayД±ran nГ¶qtЙ™",divide:"BГ¶lГјЕџdГјrmЙ™",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"NГ¶qtЙ™li verqГјl",equalSign:"BarЙ™bЙ™rlik iЕџarЙ™si",
comma:"VergГјl",dash:"Defis",period:"NГ¶qtЙ™",forwardSlash:"Г‡Й™p xЙ™tt",graveAccent:"VurДџu iЕџarЙ™si",openBracket:"AГ§Д±lan mГ¶tЙ™rizЙ™",backSlash:"TЙ™rs Г§Й™pЙ™ki xЙ™tt",closeBracket:"BaДџlanan mГ¶tЙ™rizЙ™",singleQuote:"TЙ™k dД±rnaq"});