п»ї/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","es-mx",{title:"Instrucciones de accesibilidad",contents:"Contenidos de ayuda. Para cerrar este cuadro de diГЎlogo presione ESC.",legend:[{name:"General",items:[{name:"Barra de herramientas del editor",legend:"Presione ${toolbarFocus} para navegar a la barra de herramientas. DesplГЎcese al grupo de barras de herramientas siguiente y anterior con  SHIFT + TAB. DesplГЎcese al botГіn siguiente y anterior de la barra de herramientas con FLECHA DERECHA o FLECHA IZQUIERDA. Presione SPACE o ENTER para activar el botГіn de la barra de herramientas."},
{name:"Editor de diГЎlogo",legend:"Dentro de un cuadro de diГЎlogo, pulse TAB para desplazarse hasta el siguiente elemento de diГЎlogo, pulse MAYГљS + TAB para desplazarse al elemento de diГЎlogo anterior, pulse ENTER para enviar el diГЎlogo, pulse ESC para cancelar el diГЎlogo. Cuando un cuadro de diГЎlogo tiene varias pestaГ±as, se puede acceder a la lista de pestaГ±as con ALT + F10 o con TAB como parte del orden de tabulaciГіn del diГЎlogo. Con la lista de tabuladores enfocada, mueva a la pestaГ±a siguiente y anterior con las flechas DERECHA y IZQUIERDA, respectivamente."},
{name:"MenГє contextual del editor",legend:"Presione ${contextMenu} o CLAVE DE APLICACIГ“N para abrir el menГє contextual. A continuaciГіn, vaya a la siguiente opciГіn del menГє con TAB o DOWN ARROW. DesplГЎcese a la opciГіn anterior con SHIFT + TAB o FLECHA ARRIBA. Presione SPACE o ENTER para seleccionar la opciГіn del menГє. Abra el submenГє de la opciГіn actual con ESPACIO o ENTER o FLECHA DERECHA. Vuelva al elemento de menГє principal con ESC o FLECHA IZQUIERDA. Cerrar el menГє contextual con ESC."},{name:"Editor de cuadro de lista",
legend:"Dentro de un cuadro de lista, mueva al siguiente elemento de lista con TAB O FLECHA ABAJO. Mueva al elemento anterior de la lista con MAYГљS + TAB o FLECHA ARRIBA. Presione SPACE o ENTER para seleccionar la opciГіn de lista. Presione ESC para cerrar el cuadro de lista."},{name:"Barra de ruta del elemento del editor",legend:"Presione ${elementsPathFocus} para navegar a la barra de ruta de elementos. DesplГЎcese al siguiente botГіn de elemento con TAB o FLECHA DERECHA. DesplГЎcese al botГіn anterior con SHIFT + TAB o FLECHA IZQUIERDA. Presione SPACE o ENTER para seleccionar el elemento en el editor."}]},
{name:"Comandos",items:[{name:"Comando deshacer",legend:"Presiona ${undo}"},{name:"Comando rehacer",legend:"Presiona ${redo}"},{name:"Comando negrita",legend:"Presiona ${bold}"},{name:"Comando cursiva",legend:"Presiona {italic}"},{name:"Comando subrayado",legend:"Presiona ${underline}"},{name:"Comando enlace",legend:"Presiona ${link}"},{name:"Comando colapsar barra de herramientas",legend:"Presiona ${toolbarCollapse}"},{name:"Acceda al comando de espacio de enfoque anterior",legend:"Presione ${accessPreviousSpace} para acceder al espacio de enfoque inaccesible mГЎs cercano antes del cursor, por ejemplo: dos elementos HR adyacentes. Repita la combinaciГіn de teclas para alcanzar los espacios de enfoque distantes."},
{name:"Acceder al siguiente comando de espacio de enfoque",legend:"Pulse ${accessNextSpace} para acceder al espacio de enfoque mГЎs cercano inaccesible despuГ©s del cursor, por ejemplo: dos elementos HR adyacentes. Repita la combinaciГіn de teclas para alcanzar los espacios de enfoque distantes."},{name:"Ayuda de accesibilidad",legend:"Presiona ${a11yHelp}"},{name:" Paste as plain text",legend:"Press ${pastetext}",legendEdge:"Press ${pastetext}, followed by ${paste}"}]}],tab:"Tabulador",pause:"Pausa",
capslock:"MayГєsculas",escape:"Escape",pageUp:"PГЎgina arriba",pageDown:"PГЎgina abajo",leftArrow:"Flecha izquierda",upArrow:"Flecha arriba",rightArrow:"Flecha derecha",downArrow:"Flecha abajo",insert:"Insertar",leftWindowKey:"Tecla izquierda de Windows",rightWindowKey:"Tecla derecha de Windows",selectKey:"Tecla de selecciГіn",numpad0:"Teclado numГ©rico 0",numpad1:"Teclado numГ©rico 1",numpad2:"Teclado numГ©rico 2",numpad3:"Teclado numГ©rico 3",numpad4:"Teclado numГ©rico 4",numpad5:"Teclado numГ©rico 5",numpad6:"Teclado numГ©rico 6",
numpad7:"Teclado numГ©rico 7",numpad8:"Teclado numГ©rico 8",numpad9:"Teclado numГ©rico 9",multiply:"Multiplicar",add:"Sumar",subtract:"Restar",decimalPoint:"Punto decimal",divide:"Dividir",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"NГєmeros",scrollLock:"Bloqueo de desplazamiento",semiColon:"punto y coma",equalSign:"Signo igual",comma:"Coma",dash:"GuiГіn",period:"Espacio",forwardSlash:"Diagonal",graveAccent:"Acento grave",openBracket:"Abrir parГ©ntesis",
backSlash:"Diagonal invertida",closeBracket:"Cerrar parГ©ntesis",singleQuote:"Comillas simple"});