<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");

$APPLICATION->SetTitle("Контакты");

?>
<?php $APPLICATION->IncludeComponent(
	"bitrix:news", 
	"stores", 
	array(
		"COMPONENT_TEMPLATE" => "stores",
		"IBLOCK_TYPE" => "#CONTENT_CONTACTS_IBLOCK_TYPE#",
		"IBLOCK_ID" => "#CONTENT_CONTACTS_IBLOCK_ID#",
		"NEWS_COUNT" => "20",
		"SETTINGS_USE" => "Y",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"CHECK_DATES" => "Y",
		"MAP_VENDOR" => "yandex",
		"SHOW_MAP" => "Y",
		"PHONE_SHOW" => "Y",
		"SCHEDULE_SHOW" => "Y",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "#SITE_DIR#contacts/stores/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"USE_SEARCH" => "",
		"USE_RSS" => "",
		"USE_RATING" => "",
		"USE_CATEGORIES" => "",
		"USE_REVIEW" => "",
		"USE_FILTER" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "",
		"LIST_FIELD_CODE" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "",
		"DETAIL_ACTIVE_DATE_FORMAT" => "",
		"DETAIL_FIELD_CODE" => "",
		"DETAIL_DISPLAY_TOP_PAGER" => "",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "",
		"DETAIL_PAGER_TITLE" => "",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "",
		"SET_LAST_MODIFIED" => "N",
		"SET_TITLE" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"ADD_ELEMENT_CHAIN" => "Y",
		"USE_PERMISSIONS" => "N",
		"STRICT_SECTION_CHECK" => "N",
		"NUM_NEWS" => "",
		"NUM_DAYS" => "",
		"YANDEX" => "",
		"MAX_VOTE" => "",
		"VOTE_NAMES" => "",
		"CATEGORY_IBLOCK" => "",
		"CATEGORY_CODE" => "",
		"CATEGORY_ITEMS_COUNT" => "",
		"MESSAGES_PER_PAGE" => "",
		"USE_CAPTCHA" => "",
		"REVIEW_AJAX_POST" => "",
		"PATH_TO_SMILE" => "",
		"FORUM_ID" => "",
		"URL_TEMPLATES_READ" => "",
		"SHOW_LINK_TO_FORUM" => "",
		"FILTER_NAME" => "",
		"FILTER_FIELD_CODE" => "",
		"FILTER_PROPERTY_CODE" => "",
		"LIST_PROPERTY_CODE" => array(
			0 => "ADDRESS",
			1 => "WORK_TIME",
			2 => "MAP",
			3 => "PHONE",
			4 => "PHONE_HELP",
			5 => "EMAIL",
			6 => "",
		),
		"DISPLAY_NAME" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "ADDRESS",
			1 => "WORK_TIME",
			2 => "MAP",
			3 => "PHONE",
			4 => "PHONE_HELP",
			5 => "EMAIL",
			6 => "",
		),
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SET_STATUS_404" => "Y",
		"SHOW_404" => "Y",
		"FILE_404" => "#SITE_DIR#404.php",
		"MAP" => "MAP",
		"API_KEY_MAP" => "",
		"ADDRESS" => "ADDRESS",
		"PHONE" => "PHONE",
		"EMAIL" => "EMAIL",
		"SCHEDULE" => "WORK_TIME",
		"PROPERTY_MAP" => "MAP",
		"PROPERTY_ADDRESS" => "ADDRESS",
		"PROPERTY_PHONE" => "PHONE",
		"PROPERTY_EMAIL" => "EMAIL",
		"PROPERTY_SCHEDULE" => "WORK_TIME",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_ID#/",
		)
	),
	false
) ?>
<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php") ?>
