<?php

use Kit\Origami\Helper\Config;
use \Bitrix\Main\Localization\Loc;
use Bitrix\Main\Page\Asset;
if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) {
    die();
}

Asset::getInstance()->addCss(SITE_DIR . "local/templates/.default/components/bitrix/news/kit_origami_promotions/style.css");

\Bitrix\Main\Loader::includeModule('currency');
CJSCore::Init(array('currency'));
$this->setFrameMode(true);
?>

<div class="promotion_detail">
    <?
    $ElementID = $APPLICATION->IncludeComponent(
        "bitrix:news.detail",
        "",
        [
            "DISPLAY_DATE"              => $arParams["DISPLAY_DATE"],
            "DISPLAY_NAME"              => $arParams["DISPLAY_NAME"],
            "DISPLAY_PICTURE"           => $arParams["DISPLAY_PICTURE"],
            "DISPLAY_PREVIEW_TEXT"      => $arParams["DISPLAY_PREVIEW_TEXT"],
            "IBLOCK_TYPE"               => $arParams["IBLOCK_TYPE"],
            "IBLOCK_ID"                 => $arParams["IBLOCK_ID"],
            "FIELD_CODE"                => $arParams["DETAIL_FIELD_CODE"],
            "PROPERTY_CODE"             => $arParams["DETAIL_PROPERTY_CODE"],
            "DETAIL_URL"                => $arResult["FOLDER"]
                .$arResult["URL_TEMPLATES"]["detail"],
            "SECTION_URL"               => $arResult["FOLDER"]
                .$arResult["URL_TEMPLATES"]["section"],
            "META_KEYWORDS"             => $arParams["META_KEYWORDS"],
            "META_DESCRIPTION"          => $arParams["META_DESCRIPTION"],
            "BROWSER_TITLE"             => $arParams["BROWSER_TITLE"],
            "SET_CANONICAL_URL"         => $arParams["DETAIL_SET_CANONICAL_URL"],
            "DISPLAY_PANEL"             => $arParams["DISPLAY_PANEL"],
            "SET_LAST_MODIFIED"         => $arParams["SET_LAST_MODIFIED"],
            "SET_TITLE"                 => $arParams["SET_TITLE"],
            "MESSAGE_404"               => $arParams["MESSAGE_404"],
            "SET_STATUS_404"            => $arParams["SET_STATUS_404"],
            "SHOW_404"                  => $arParams["SHOW_404"],
            "FILE_404"                  => $arParams["FILE_404"],
            "INCLUDE_IBLOCK_INTO_CHAIN" => $arParams["INCLUDE_IBLOCK_INTO_CHAIN"],
            "ADD_SECTIONS_CHAIN"        => $arParams["ADD_SECTIONS_CHAIN"],
            "ACTIVE_DATE_FORMAT"        => $arParams["DETAIL_ACTIVE_DATE_FORMAT"],
            "CACHE_TYPE"                => $arParams["CACHE_TYPE"],
            "CACHE_TIME"                => $arParams["CACHE_TIME"],
            "CACHE_GROUPS"              => $arParams["CACHE_GROUPS"],
            "USE_PERMISSIONS"           => $arParams["USE_PERMISSIONS"],
            "GROUP_PERMISSIONS"         => $arParams["GROUP_PERMISSIONS"],
            "DISPLAY_TOP_PAGER"         => $arParams["DETAIL_DISPLAY_TOP_PAGER"],
            "DISPLAY_BOTTOM_PAGER"      => $arParams["DETAIL_DISPLAY_BOTTOM_PAGER"],
            "PAGER_TITLE"               => $arParams["DETAIL_PAGER_TITLE"],
            "PAGER_SHOW_ALWAYS"         => "N",
            "PAGER_TEMPLATE"            => $arParams["DETAIL_PAGER_TEMPLATE"],
            "PAGER_SHOW_ALL"            => $arParams["DETAIL_PAGER_SHOW_ALL"],
            "CHECK_DATES"               => $arParams["CHECK_DATES"],
            "ELEMENT_ID"                => $arResult["VARIABLES"]["ELEMENT_ID"],
            "ELEMENT_CODE"              => $arResult["VARIABLES"]["ELEMENT_CODE"],
            "SECTION_ID"                => $arResult["VARIABLES"]["SECTION_ID"],
            "SECTION_CODE"              => $arResult["VARIABLES"]["SECTION_CODE"],
            "IBLOCK_URL"                => $arResult["FOLDER"]
                .$arResult["URL_TEMPLATES"]["news"],
            "USE_SHARE"                 => $arParams["USE_SHARE"],
            "SHARE_HIDE"                => $arParams["SHARE_HIDE"],
            "SHARE_TEMPLATE"            => $arParams["SHARE_TEMPLATE"],
            "SHARE_HANDLERS"            => $arParams["SHARE_HANDLERS"],
            "SHARE_SHORTEN_URL_LOGIN"   => $arParams["SHARE_SHORTEN_URL_LOGIN"],
            "SHARE_SHORTEN_URL_KEY"     => $arParams["SHARE_SHORTEN_URL_KEY"],
            "ADD_ELEMENT_CHAIN"         => (isset($arParams["ADD_ELEMENT_CHAIN"])
                ? $arParams["ADD_ELEMENT_CHAIN"] : ''),
            'STRICT_SECTION_CHECK'      => (isset($arParams['STRICT_SECTION_CHECK'])
                ? $arParams['STRICT_SECTION_CHECK'] : ''),
        ],
        $component
    );
    global $detailPromotion;
    if($detailPromotion) {
        $intSectionID = $APPLICATION->IncludeComponent(
            "bitrix:catalog.section",
            "origami_section",
            [
                "IBLOCK_ID"                 => Config::get("IBLOCK_ID"),
                "IBLOCK_TYPE"               => Config::get("IBLOCK_TYPE"),
                "ELEMENT_SORT_FIELD"        => "rand",
                "ELEMENT_SORT_ORDER"        => "id",
                "ELEMENT_SORT_FIELD2"       => "desc",
                "ELEMENT_SORT_ORDER2"       => "desc",
                "PROPERTY_CODE"             => [
                    1 => "TIP_SIM_KARTY",
                    2 => "RAZMER_OPERATIVNOY_PAMYATI",
                    3 => "OBEM_MOROZILNOY_KAMERY",
                    4 => "VYSOTA_PODDONA",
                    5 => "KONSTRUKTSIYA",
                    6 => "TIP_PAMYATI",
                    7 => "VAROCHNAYA_PANEL",
                    8 => "MATERIAL_PEREDNIKH_STENOK",
                    9 => "VERSIYA_OS",
                    10 => "VIDEOKARTA",
                    11 => "DUKHOVKA",
                    12 => "PANEL_UPRAVLENIYA",
                    13 => "KOLICHESTVO_SIM_KART",
                    14 => "OBEM_ZHESTKOGO_DISKA",
                    15 => "NOMINALNAYA_POTREBLYAEMAYA_MOSHCHNOST",
                    16 => "PROTIVOSKOLZYASHCHEE_POKRYTIE_DNA",
                    17 => "CML2_BAR_CODE",
                    18 => "CML2_ARTICLE",
                    19 => "CML2_ATTRIBUTES",
                    20 => "CML2_TRAITS",
                    21 => "CML2_BASE_UNIT",
                    22 => "CML2_TAXES",
                    23 => "MORE_PHOTO",
                    24 => "FILES",
                    25 => "CML2_MANUFACTURER",
                    26 => "RAZMERY_SHXVXT",
                    27 => "KOLICHESTVO_YADER",
                    28 => "RABOCHAYA_POVERKHNOST",
                    29 => "GABARITY_SHKHVKHD",
                    30 => "BLOG_POST_ID",
                    31 => "BLOG_COMMENTS_CNT",
                    32 => "DIAGONAL_EKRANA",
                    33 => "BLOK_PITANIYA",
                    34 => "KOLICHESTVO_KONFOROK",
                    35 => "TIP_PEREDNEGO_STEKLA",
                    36 => "TIP_EKRANA",
                    37 => "KORPUS",
                    38 => "TIP_DUKHOVKI",
                    39 => "RAMA_ROST_VELOSIPEDISTA_SM",
                    40 => "RAZMER_IZOBRAZHENIYA",
                    41 => "RAZRABOTCHIK_VIDEOKARTY",
                    42 => "DIAGONAL_EKRANA_1",
                    43 => "MATERIAL_RAMY",
                    44 => "TYLOVAYA_FOTOKAMERA",
                    45 => "LINEYKA_PROTSESSOROV",
                    46 => "RAZRESHENIE_EKRANA",
                    47 => "RAZMERY_RAMY",
                    48 => "FRONTALNAYA_KAMERA",
                    49 => "SOCKET",
                    50 => "TIP_ZHESTKOGO_DISKA",
                    51 => "DIAMETR_KOLES",
                    52 => "RAZEM_DLYA_NAUSHNIKOV",
                    53 => "KOLICHESTVO_YADER_1",
                    54 => "TIP_PAMYATI_2",
                    55 => "MATERIAL_OBODA",
                    56 => "SPUTNIKOVAYA_NAVIGATSIYA",
                    57 => "CHASTOTA_PROTSESSORA",
                    58 => "WI_FI",
                    59 => "PEREDNIY_TORMOZ",
                    60 => "PROTSESSOR",
                    61 => "YADRO",
                    62 => "BLUETOOTH",
                    63 => "ZADNIY_TORMOZ",
                    64 => "KOLICHESTVO_YADER_PROTSESSORA",
                    65 => "INTEGRIROVANNOE_GRAFICHESKOE_YADRO",
                    66 => "VYKHOD_HDMI",
                    67 => "KOLICHESTVO_SKOROSTEY",
                    68 => "VIDEOPROTSESSOR",
                    69 => "SOCKET_1",
                    70 => "VYKHOD_AUDIO_NAUSHNIKI",
                    71 => "MOSHCHNOST",
                    72 => "OBEM_VSTROENNOY_PAMYATI",
                    73 => "FORM_FAKTOR",
                    74 => "RAZRESHENIE_VEB_KAMERY",
                    75 => "SHAG_TSEPI",
                    76 => "OBEM_OPERATIVNOY_PAMYATI",
                    77 => "TIP_PAMYATI_1",
                    78 => "PROIZVODITEL_TELEFONA",
                    79 => "DLINA_SHINY",
                    80 => "SLOT_DLYA_KART_PAMYATI",
                    81 => "KOLICHESTVO_SLOTOV_PAMYATI",
                    82 => "MODELI_TELEFONA",
                    83 => "OBEM_DVIGATELYA",
                    84 => "EMKOST_AKKUMULYATORA",
                    85 => "BIOS",
                    86 => "MATERIAL_1",
                    87 => "EMKOST_TOPLIVNOGO_BAKA",
                    88 => "TIP_RAZEMA_DLYA_ZARYADKI",
                    89 => "SATA",
                    90 => "PROZRACHNYY",
                    91 => "EMKOST_MASLYANOGO_BAKA",
                    92 => "GROMKAYA_SVYAZ",
                    93 => "ETHERNET",
                    94 => "TIP_KAMERY",
                    95 => "FUNKTSII_I_VOZMOZHNOSTI",
                    96 => "KONSTRUKTSIYA_AKKUMULYATOR",
                    97 => "RAZEMY_NA_ZADNEY_PANELI",
                    98 => "DIAFRAGMA_1",
                    99 => "KOMPLEKT_POSTAVKI",
                    100 => "TIP_AKKUMULYATORA",
                    101 => "INTERFEYS_PODKLYUCHENIYA",
                    102 => "OBSHCHEE_CHISLO_PIKSELOV",
                    103 => "TIP",
                    104 => "BYSTRAYA_ZARYADKA",
                    105 => "PREDNAZNACHENIE",
                    106 => "MAKSIMALNOE_RAZRESHENIE",
                    107 => "KONSTRUKTSIYA_1",
                    108 => "MAKS_VYKHODNOY_TOK",
                    109 => "TIP_BESPROVODNOY_SVYAZI",
                    110 => "CHUVSTVITELNOST",
                    111 => "MODEL",
                    112 => "RAZEM_PODKLYUCHENIYA",
                    113 => "KOLICHESTVO_KLAVISH",
                    114 => "BALANS_BELOGO_1",
                    115 => "VID_ZASTEZHKI",
                    116 => "KOLICHESTVO_RAZEMOV",
                    117 => "KOLICHESTVO_PROGRAMMIRUEMYKH_KLAVISH",
                    118 => "VSPYSHKA",
                    119 => "DLINA_IZDELIYA_PO_SPINKE",
                    120 => "KABEL_V_KOMPLEKTE",
                    121 => "DLINA_PROVODA",
                    122 => "ZAPIS_VIDEO",
                    123 => "POKROY",
                    124 => "TIP_NOSITELYA",
                    125 => "INTERFEYS_PODKLYUCHENIYA_1",
                    126 => "USTANOVKA",
                    127 => "POL",
                    128 => "MAKSIMALNOE_RAZRESHENIE_VIDEOSEMKI",
                    129 => "PODSVETKA_KLAVISH",
                    130 => "TIP_ZAGRUZKI",
                    131 => "POLNOTA_OBUVI_EUR",
                    132 => "ZOOM",
                    133 => "TSIFROVOY_BLOK",
                    134 => "MAKSIMALNAYA_ZAGRUZKA_BELYA",
                    135 => "SEZON",
                    136 => "DIAFRAGMA",
                    137 => "KOLICHESTVO_DOPOLNITELNYKH_KLAVISH",
                    138 => "DISPLEY",
                    139 => "STRANA_PROIZVODITEL",
                    140 => "DIAMETR_FILTRA",
                    141 => "MAKSIMALNYY_RAZMER_EKRANA",
                    142 => "GABARITY_SHXGXV",
                    143 => "TIP_POSADKI",
                    144 => "ZHK_EKRAN",
                    145 => "MATERIAL",
                    146 => "KLASS_ENERGOPOTREBLENIYA",
                    147 => "UKHOD_ZA_VESHCHAMI",
                    148 => "VIDOISKATEL",
                    149 => "TIP_SOEDINENIYA",
                    150 => "RASKHOD_VODY_ZA_STIRKU",
                    151 => "FAKTURA_MATERIALA",
                    152 => "BALANS_BELOGO",
                    153 => "MIKROFON",
                    154 => "KOLICHESTVO_PROGRAMM",
                    155 => "KHIT",
                    156 => "ZHESTKIY_DISK",
                    157 => "SISTEMA_AKTIVNOGO_SHUMOPODAVLENIYA",
                    158 => "TERMOSTAT",
                    159 => "NOVINKA",
                    160 => "OPERATIVNAYA_PAMYAT",
                    161 => "MINIMALNAYA_VOSPROIZVODIMAYA_CHASTOTA",
                    162 => "NAZNACHENIE",
                    163 => "RASPRODAZHA",
                    164 => "RAZEMY",
                    165 => "MAKSIMALNAYA_VOSPROIZVODIMAYA_CHASTOTA",
                    166 => "POKRYTIE",
                    167 => "SHIRINA_SKASHIVANIYA",
                    168 => "PODDERZHIVAEMYE_NOSITELI",
                    169 => "TIP_KREPLENIYA",
                    170 => "SPOSOB_MONTAZHA",
                    171 => "VYSOTA_SKASHIVANIYA",
                    172 => "PODDERZHIVAEMYE_FORMATY",
                    173 => "MOROZILNAYA_KAMERA",
                    174 => "MATERIAL_2",
                    175 => "MOSHCHNOST_DVIGATELYA",
                    176 => "OBEM_VSTROENNOY_FLESH_PAMYATI",
                    177 => "MATERIAL_POKRYTIYA",
                    178 => "FORMA",
                    179 => "USTROYSTVO_DLYA_CHTENIYA_KART_PAMYATI",
                    180 => "ENERGOPOTREBLENIE",
                    181 => "OBEM",
                    182 => "ISTOCHNIK_PITANIYA",
                    183 => "KOLICHESTVO_KAMER",
                    184 => "UGLOVAYA_KONSTRUKTSIYA",
                    185 => "VOZRASTNYE_OGRANICHENIYA",
                    186 => "KOLICHESTVO_DVEREY",
                    187 => "MODIFIKATSIYA",
                    188 => "IZ_CHEGO_SDELANO_SOSTAV",
                    189 => "OBSHCHIY_OBEM",
                    190 => "GIDROMASSAZH",
                    191 => "SOVMESTIMOST",
                    192 => "OBEM_KHOLODILNOY_KAMERY",
                    193 => "FORMA_1",
                    194 => "INTERFEYS",
                    195 => "MATERIAL_PODDONA",
                    196 => "KREPLENIE_MIKROFONA",
                    197 => "LINEYKA_PROTSESSORA",
                ],
                "PROPERTY_CODE_MOBILE"      => [],
                "META_KEYWORDS"             => "-",
                "META_DESCRIPTION"          => "-",
                "BROWSER_TITLE"             => "-",
                "SET_LAST_MODIFIED"         => "N",
                "INCLUDE_SUBSECTIONS"       => "Y",
                "BASKET_URL"                => Config::get('BASKET_PAGE'),
                "ACTION_VARIABLE"           => "action",
                "PRODUCT_ID_VARIABLE"       => "id",
                "SECTION_ID_VARIABLE"       => "SECTION_ID",
                "PRODUCT_QUANTITY_VARIABLE" => "quantity",
                "PRODUCT_PROPS_VARIABLE"    => "prop",
                "FILTER_NAME"               => "detailPromotion",
                "CACHE_FILTER"              => "Y",
                "CACHE_GROUPS"              => "Y",
                "CACHE_TIME"                => "36000000",
                "CACHE_TYPE"                => "A",
                "SET_TITLE"                 => "N",
                "MESSAGE_404"               => "",
                "SET_STATUS_404"            => "Y",
                'SHOW_ALL_WO_SECTION'       => 'Y',
                "SHOW_404"                  => "N",
                "DISPLAY_COMPARE"           => "Y",
                "PAGE_ELEMENT_COUNT"        => 100,
                "LINE_ELEMENT_COUNT"        => 5,
                "PRICE_CODE"                => \KitOrigami::GetComponentPrices(["BASE","OPT","SMALL_OPT"]),
                "USE_PRICE_COUNT"           => "N",
                "SHOW_PRICE_COUNT"          => "1",

                "PRICE_VAT_INCLUDE"          => "Y",
                "USE_PRODUCT_QUANTITY"       => "Y",
                "ADD_PROPERTIES_TO_BASKET"   => "Y",
                "PARTIAL_PRODUCT_PROPERTIES" => "N",
                "PRODUCT_PROPERTIES"         => [
                ],

                "DISPLAY_TOP_PAGER"               => "N",
                "DISPLAY_BOTTOM_PAGER"            => "N",
                "PAGER_TITLE"                     => Loc::getMessage('PAGER_TITLE'),
                "PAGER_SHOW_ALWAYS"               => "",
                "PAGER_TEMPLATE"                  => "",
                "PAGER_DESC_NUMBERING"            => "N",
                "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
                "PAGER_SHOW_ALL"                  => "N",
                "PAGER_BASE_LINK_ENABLE"          => "N",
                "PAGER_BASE_LINK"                 => "N",
                "PAGER_PARAMS_NAME"               => "N",
                "LAZY_LOAD"                       => "N",
                "MESS_BTN_LAZY_LOAD"              => "N",
                "LOAD_ON_SCROLL"                  => "N",

                "OFFERS_CART_PROPERTIES" => [
                    0 => "SIZES_SHOES",
                    1 => "SIZES_CLOTHES",
                    2 => "COLOR_REF",
                ],
                "OFFERS_FIELD_CODE"      => [
                    0 => "NAME",
                    1 => "PREVIEW_PICTURE",
                    2 => "DETAIL_PICTURE",
                    3 => "DETAIL_PAGE_URL",
                ],
                "OFFERS_PROPERTY_CODE"   => [
                    1  => "CML2_BAR_CODE",
                    2  => "CML2_ARTICLE",
                    5  => "CML2_BASE_UNIT",
                    7  => "MORE_PHOTO",
                    8  => "FILES",
                    9  => "CML2_MANUFACTURER",
                    10 => "PROTSESSOR",
                    11 => "CHASTOTA_PROTSESSORA",
                    12 => "KOLICHESTVO_YADER_PROTSESORA",
                    13 => "OBEM_OPERATICHNOY_PAMYATI",
                    14 => "TIP_VIDEOKARTY",
                    15 => "OBEM_VIDEOPAMYATI",
                    16 => "USTANOVLENNAYA_OS",
                    17 => "OBEM_PAMYATI",
                    18 => "RAZMER",
                    19 => "TSVET",
                    20 => "TSVET_1",
                    21 => "VIDEOKARTA",
                ],
                "OFFERS_SORT_FIELD"      => "sort",
                "OFFERS_SORT_ORDER"      => "id",
                "OFFERS_SORT_FIELD2"     => "desc",
                "OFFERS_SORT_ORDER2"     => "desc",
                "OFFERS_LIMIT"           => 0,

                "SECTION_URL"               => SITE_DIR
                    .'catalog/#SECTION_CODE_PATH#/',
                "DETAIL_URL"                => SITE_DIR
                    .'catalog/#SECTION_CODE_PATH#/#ELEMENT_CODE#/',
                "USE_MAIN_ELEMENT_SECTION"  => "N",
                'CONVERT_CURRENCY'          => "N",
                'HIDE_NOT_AVAILABLE'        => "N",
                'HIDE_NOT_AVAILABLE_OFFERS' => "N",

                'LABEL_PROP'                  => [
                    0 => "RASPRODAZHA",
                ],
                'LABEL_PROP_MOBILE'           => [],
                'ADD_PICT_PROP'               => "MORE_PHOTO",
                'PRODUCT_DISPLAY_MODE'        => "Y",
                'OFFER_ADD_PICT_PROP'         => "MORE_PHOTO",
                'OFFER_TREE_PROPS'            => [
                    "PROTSESSOR",
                    "OBEM_OPERATICHNOY_PAMYATI",
                    "OBEM_PAMYATI",
                    "RAZMER",
                    "CHASTOTA_PROTSESSORA",
                    "TIP_VIDEOKARTY",
                    "TSVET",
                    "KOLICHESTVO_YADER_PROTSESORA",
                    "OBEM_VIDEOPAMYATI",
                    "TSVET_1",
                    "USTANOVLENNAYA_OS",
                    "CML2_MANUFACTURER",
                ],
                'PRODUCT_SUBSCRIPTION'        => "Y",
                'SHOW_DISCOUNT_PERCENT'       => "Y",
                'SHOW_OLD_PRICE'              => "Y",
                'SHOW_MAX_QUANTITY'           => "Y",
                "MESS_BTN_ADD_TO_BASKET"      => Loc::getMessage('MESS_BTN_ADD_TO_BASKET'),
                "MESS_BTN_BUY"                => Loc::getMessage('MESS_BTN_BUY'),
                "MESS_BTN_COMPARE"            => Loc::getMessage('MESS_BTN_COMPARE'),
                "MESS_BTN_DETAIL"             => Loc::getMessage('MESS_BTN_DETAIL'),
                "MESS_BTN_SUBSCRIBE"          => Loc::getMessage('MESS_BTN_SUBSCRIBE'),
                "MESS_NOT_AVAILABLE"          => Loc::getMessage('MESS_NOT_AVAILABLE'),
                "MESS_RELATIVE_QUANTITY_MANY" => Loc::getMessage('MESS_RELATIVE_QUANTITY_MANY'),
                "MESS_RELATIVE_QUANTITY_FEW"  => Loc::getMessage('MESS_RELATIVE_QUANTITY_FEW'),
                "MESS_RELATIVE_QUANTITY_NO"   => Loc::getMessage('MESS_RELATIVE_QUANTITY_NO'),
                'USE_VOTE_RATING'             => "Y",
                'TEMPLATE_THEME'              => "",
                "ADD_SECTIONS_CHAIN"          => "N",
                'ADD_TO_BASKET_ACTION'        => "ADD",
                'COMPARE_PATH'                => Config::get('COMPARE_PAGE'),
                'COMPARE_NAME'                => "CATALOG_COMPARE_LIST",
                'USE_COMPARE_LIST'            => 'Y',
                'ACTION_PRODUCTS' => array("ADMIN"),
                "ACTION_PRODUCTS" => array(
                    0 => "ADMIN",
                ),
                "VARIANT_LIST_VIEW" => "ADMIN",
                "SHOW_SLIDER" => "N",
                'SECTION_NAME' => Loc::getMessage('SECT_PROMO_BLOCK_NAME')
            ],
            false
        );
    }
    ?>
    <div class="puzzle_block-form-promotion-wrapper">
        <?
        CModule::IncludeModule('form');
        $FORM_SID = "QUESTIONS";
        $rsForm = CForm::GetBySID($FORM_SID);
        $arForm = $rsForm->Fetch();
        $APPLICATION->IncludeComponent(
            "bitrix:form.result.new",
            "origami_webform_2",
            Array(
                "CACHE_TIME" => "3600",
                "CACHE_TYPE" => "A",
                "CHAIN_ITEM_LINK" => "",
                "CHAIN_ITEM_TEXT" => "",
                "COMPOSITE_FRAME_MODE" => "A",
                "COMPOSITE_FRAME_TYPE" => "AUTO",
                "EDIT_URL" => "",
                "IGNORE_CUSTOM_TEMPLATE" => "N",
                "LIST_URL" => "",
                "SEF_MODE" => "N",
                "SUCCESS_URL" => "",
                "USE_EXTENDED_ERRORS" => "N",
                "VARIABLE_ALIASES" => Array(
                    "RESULT_ID" => "RESULT_ID",
                    "WEB_FORM_ID" => "WEB_FORM_ID"
                ),
                "WEB_FORM_ID" => $arForm['ID']
            )
        );
        ?>
        <div class="puzzle_block_promotion_return">
            <a class="return" href="<?=$arResult['FOLDER']?>">
			<span class="return_inner">
				<?=GetMessage('RETURN')?>
			</span>
            </a>
        </div>
    </div>
</div>
