<?php if (defined("B_PROLOG_INCLUDED") && B_PROLOG_INCLUDED === true) ?>
<?php

use intec\core\helpers\ArrayHelper;
use intec\core\io\Path;

$arParameters = [
    /** Data Source */
    'HIDE_NOT_AVAILABLE',
    'HIDE_NOT_AVAILABLE_OFFERS',

    /** Filter */
    'USE_FILTER',
    'FILTER_FIELD_CODE',
    'FILTER_PROPERTY_CODE',
    'FILTER_PRICE_CODE',
    'FILTER_OFFERS_FIELD_CODE',
    'FILTER_OFFERS_PROPERTY_CODE',

    /** Reviews */
    'USE_REVIEW',
    'MESSAGES_PER_PAGE',
    'USE_CAPTCHA',
    'REVIEW_AJAX_POST',
    'PATH_TO_SMILE',
    'FORUM_ID',
    'URL_TEMPLATES_READ',
    'SHOW_LINK_TO_FORUM',

    /** Compare */
    'USE_COMPARE',
    'COMPARE_NAME',
    'COMPARE_FIELD_CODE',
    'COMPARE_PROPERTY_CODE',
    'COMPARE_OFFERS_FIELD_CODE',
    'COMPARE_OFFERS_PROPERTY_CODE',
    'COMPARE_ELEMENT_SORT_FIELD',
    'COMPARE_ELEMENT_SORT_ORDER',
    'DISPLAY_ELEMENT_SELECT_BOX',
    'ELEMENT_SORT_FIELD_BOX',
    'ELEMENT_SORT_ORDER_BOX',
    'ELEMENT_SORT_FIELD_BOX2',
    'ELEMENT_SORT_ORDER_BOX2',
    'PRICE_CODE',
    'USE_PRICE_COUNT',
    'SHOW_PRICE_COUNT',
    'PRICE_VAT_INCLUDE',
    'PRICE_VAT_SHOW_VALUE',
    'CONVERT_CURRENCY',
    'CURRENCY_ID',
    'BASKET_URL',
    'USE_PRODUCT_QUANTITY',
    'ADD_PROPERTIES_TO_BASKET',
    'PRODUCT_PROPS_VARIABLE',
    'PARTIAL_PRODUCT_PROPERTIES',
    'PRODUCT_PROPERTIES',
    'OFFERS_CART_PROPERTIES',
    'SHOW_TOP_ELEMENTS',
    'TOP_ELEMENT_COUNT',
    'TOP_LINE_ELEMENT_COUNT',
    'TOP_ELEMENT_SORT_FIELD',
    'TOP_ELEMENT_SORT_ORDER',
    'TOP_ELEMENT_SORT_FIELD2',
    'TOP_ELEMENT_SORT_ORDER2',
    'TOP_PROPERTY_CODE',
    'TOP_OFFERS_FIELD_CODE',
    'TOP_OFFERS_PROPERTY_CODE',
    'TOP_OFFERS_LIMIT',

    /** Elements */
    'LIST_OFFERS_FIELD_CODE',
    'LIST_OFFERS_PROPERTY_CODE',
    'LIST_OFFERS_LIMIT',

    /** Detail */
    'SHOW_DEACTIVATED',
    'DETAIL_OFFERS_FIELD_CODE',
    'DETAIL_BACKGROUND_IMAGE',

    /** Links */
    'LINK_IBLOCK_TYPE',
    'LINK_IBLOCK_ID',
    'LINK_PROPERTY_SID',
    'LINK_ELEMENTS_URL',

    /** Block "Also buy" */
    'USE_ALSO_BUY',
    'ALSO_BUY_ELEMENT_COUNT',
    'ALSO_BUY_MIN_BUYES',

    /** Block "Gifts" */
    'USE_GIFTS_DETAIL',
    'USE_GIFTS_SECTION',
    'USE_GIFTS_MAIN_PR_SECTION_LIST',
    'GIFTS_DETAIL_PAGE_ELEMENT_COUNT',
    'GIFTS_DETAIL_HIDE_BLOCK_TITLE',
    'GIFTS_DETAIL_BLOCK_TITLE',
    'GIFTS_DETAIL_TEXT_LABEL_GIFT',
    'GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT',
    'GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE',
    'GIFTS_SECTION_LIST_BLOCK_TITLE',
    'GIFTS_SECTION_LIST_TEXT_LABEL_GIFT',
    'GIFTS_SHOW_DISCOUNT_PERCENT',
    'GIFTS_SHOW_OLD_PRICE',
    'GIFTS_SHOW_NAME',
    'GIFTS_SHOW_IMAGE',
    'GIFTS_MESS_BTN_BUY',
    'GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT',
    'GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE',
    'GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE',

    /** Stores */
    'USE_STORE',
    'STORES',
    'USE_MIN_AMOUNT',
    'USER_FIELDS',
    'FIELDS',
    'MIN_AMOUNT',
    'SHOW_EMPTY_STORE',
    'SHOW_GENERAL_STORE_INFORMATION',
    'STORE_PATH',
    'MAIN_TITLE',

    /** Offers */
    'OFFERS_SORT_FIELD',
    'OFFERS_SORT_ORDER',
    'OFFERS_SORT_FIELD2',
    'OFFERS_SORT_ORDER2',

    /** Special */
    'COMPATIBLE_MODE',
    'USE_ELEMENT_COUNTER',
    'DISABLE_INIT_JS_IN_COMPONENT',
    'DETAIL_SET_VIEWED_IN_COMPONENT'
];

$oPath = Path::from(__DIR__.'/../settings/empty/control.js')->toRelative()->asAbsolute();
$sPath = $oPath->getValue('/');

foreach ($arParameters as $sParameter) {
    $arTemplateParameters[$sParameter] = [
        'HIDDEN' => 'Y',
        'TYPE' => 'CUSTOM',
        'JS_FILE' => $sPath,
        'JS_EVENT' => 'initControlEmpty'
    ];
}