<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php") ?>
<?php

$APPLICATION->SetTitle("Оформление заказа");

?>
<? $APPLICATION->IncludeComponent(
    "bitrix:sale.order.ajax",
    "simple.1",
    array(
        "PAY_FROM_ACCOUNT" => "N",
        "ONLY_FULL_PAY_FROM_ACCOUNT" => "N",
        "ALLOW_AUTO_REGISTER" => "Y",
        "ALLOW_APPEND_ORDER" => "Y",
        "SEND_NEW_USER_NOTIFY" => "Y",
        "DELIVERY_NO_AJAX" => "Y",
        "SHOW_NOT_CALCULATED_DELIVERIES" => "L",
        "DELIVERY_NO_SESSION" => "Y",
        "TEMPLATE_LOCATION" => "popup",
        "DELIVERY_TO_PAYSYSTEM" => "d2p",
        "SHOW_VAT_PRICE" => "Y",
        "USE_PREPAYMENT" => "N",
        "COMPATIBLE_MODE" => "Y",
        "USE_PRELOAD" => "Y",
        "ALLOW_USER_PROFILES" => "Y",
        "ALLOW_NEW_PROFILE" => "Y",
        "TEMPLATE_THEME" => "site",
        "SHOW_ORDER_BUTTON" => "final_step",
        "SHOW_TOTAL_ORDER_BUTTON" => "Y",
        "SHOW_PAY_SYSTEM_LIST_NAMES" => "Y",
        "SHOW_PAY_SYSTEM_INFO_NAME" => "Y",
        "SHOW_DELIVERY_LIST_NAMES" => "Y",
        "SHOW_DELIVERY_INFO_NAME" => "Y",
        "SHOW_DELIVERY_PARENT_NAMES" => "Y",
        "SHOW_STORES_IMAGES" => "Y",
        "SKIP_USELESS_BLOCK" => "Y",
        "BASKET_POSITION" => "after",
        "SHOW_BASKET_HEADERS" => "Y",
        "DELIVERY_FADE_EXTRA_SERVICES" => "Y",
        "SHOW_COUPONS_BASKET" => "Y",
        "SHOW_COUPONS_DELIVERY" => "N",
        "SHOW_COUPONS_PAY_SYSTEM" => "N",
        "SHOW_NEAREST_PICKUP" => "Y",
        "DELIVERIES_PER_PAGE" => "9",
        "PAY_SYSTEMS_PER_PAGE" => "9",
        "PICKUPS_PER_PAGE" => "5",
        "SHOW_PICKUP_MAP" => "Y",
        "SHOW_MAP_IN_PROPS" => "N",
        "PROPS_FADE_LIST_1" => array(
            0 => "1",
            1 => "2",
            2 => "3",
            3 => "4",
            4 => "7",
        ),
        "PROPS_FADE_LIST_2" => array(
            0 => "8",
            1 => "9",
            2 => "10",
            3 => "11",
            4 => "12",
            5 => "13",
            6 => "14",
            7 => "15",
            8 => "16",
            9 => "19",
        ),
        "USER_CONSENT" => "N",
        "ACTION_VARIABLE" => "action",
        "PATH_TO_BASKET" => "#SITE_DIR#personal/basket/",
        "PATH_TO_PERSONAL" => "#SITE_DIR#personal/profile/",
        "PATH_TO_PAYMENT" => "#SITE_DIR#personal/basket/payment/",
        "PATH_TO_AUTH" => "#SITE_DIR#personal/profile/",
        "SET_TITLE" => "Y",
        "DISABLE_BASKET_REDIRECT" => "Y",
        "PRODUCT_COLUMNS_VISIBLE" => array(
            0 => "PREVIEW_PICTURE",
            1 => "PROPS",
            2 => "NOTES",
            3 => "DISCOUNT_PRICE_PERCENT_FORMATED",
            4 => "PRICE_FORMATED",
            5 => "WEIGHT_FORMATED",
        ),
        "ADDITIONAL_PICT_PROP_12" => "-",
        "ADDITIONAL_PICT_PROP_13" => "-",
        "ADDITIONAL_PICT_PROP_31" => "-",
        "ADDITIONAL_PICT_PROP_43" => "-",
        "BASKET_IMAGES_SCALING" => "adaptive",
        "SERVICES_IMAGES_SCALING" => "adaptive",
        "PRODUCT_COLUMNS_HIDDEN" => array(
            0 => "PREVIEW_PICTURE",
            1 => "DETAIL_PICTURE",
            2 => "PREVIEW_TEXT",
            3 => "PROPS",
            4 => "NOTES",
            5 => "DISCOUNT_PRICE_PERCENT_FORMATED",
            6 => "PRICE_FORMATED",
            7 => "WEIGHT_FORMATED",
        ),
        "USE_YM_GOALS" => "N",
        "USE_ENHANCED_ECOMMERCE" => "N",
        "USE_CUSTOM_MAIN_MESSAGES" => "N",
        "USE_CUSTOM_ADDITIONAL_MESSAGES" => "N",
        "USE_CUSTOM_ERROR_MESSAGES" => "N",
        "ADDITIONAL_PICT_PROP_4" => "-",
        "ADDITIONAL_PICT_PROP_5" => "-",
        "ADDITIONAL_PICT_PROP_20" => "-",
        "ADDITIONAL_PICT_PROP_21" => "-",
        "SPOT_LOCATION_BY_GEOIP" => "Y",
        "PICKUP_MAP_TYPE" => "yandex",
        "USE_PHONE_NORMALIZATION" => "Y",
        "ADDITIONAL_PICT_PROP_16" => "-",
        "ADDITIONAL_PICT_PROP_44" => "-",
        "ADDITIONAL_PICT_PROP_62" => "-",
        "ADDITIONAL_PICT_PROP_63" => "-",
        "HIDE_ORDER_DESCRIPTION" => "N",
        "ORDER_GROUP_PROPS" => "1",
        "ORDER_PROP_DELIVERY" => ""
    ),
    false
) ?>
<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php") ?>
