<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");

$APPLICATION->SetTitle("Каталог товаров");

?>
<? $APPLICATION->IncludeComponent(
    "bitrix:catalog",
    "catalog.1",
    array(
        "IBLOCK_TYPE" => "#CATALOGS_PRODUCTS_IBLOCK_TYPE#",
        "IBLOCK_ID" => "#CATALOGS_PRODUCTS_IBLOCK_ID#",
        "SETTINGS_USE" => "Y",
        "DELAY_USE" => "Y",
        "MENU_TEMPLATE" => "1",
        "MENU_ROOT" => "left",
        "MENU_CHILD" => "left",
        "MENU_LEVEL" => "4",
        "MENU_IBLOCK_TYPE" => "#CATALOGS_PRODUCTS_IBLOCK_TYPE#",
        "MENU_IBLOCK_ID" => "#CATALOGS_PRODUCTS_IBLOCK_ID#",
        "ORDER_FAST_USE" => "N",
        "FORM_ID" => "#FORMS_PRODUCT_ID#",
        "FORM_PROPERTY_PRODUCT" => "#FORMS_PRODUCT_FIELDS_PRODUCT_ID#",
        "FORM_TEMPLATE" => ".default",
        "HIDE_NOT_AVAILABLE" => "N",
        "HIDE_NOT_AVAILABLE_OFFERS" => "N",
        "PROPERTY_MARKS_RECOMMEND" => "RECOMMEND",
        "PROPERTY_MARKS_NEW" => "NEW",
        "PROPERTY_MARKS_HIT" => "HIT",
        "PROPERTY_ORDER_USE" => "ORDER_USE",
        "PROPERTY_ARTICLE" => "ARTICLE",
        "PROPERTY_BRAND" => "BRAND",
        "PROPERTY_PICTURES" => "PICTURES",
        "PROPERTY_SERVICES" => "SERVICES",
        "PROPERTY_DOCUMENTS" => "DOCUMENTS",
        "PROPERTY_ADDITIONAL" => "ADDITIONAL",
        "PROPERTY_ASSOCIATED" => "ASSOCIATED",
        "PROPERTY_RECOMMENDED" => "RECOMMENDED",
        "PROPERTY_VIDEO" => "VIDEO",
        "OFFERS_PROPERTY_ARTICLE" => "ARTICLE",
        "OFFERS_PROPERTY_PICTURES" => "PICTURES",
        "VIDEO_IBLOCK_TYPE" => "#CONTENT_VIDEO_IBLOCK_TYPE#",
        "VIDEO_IBLOCK_ID" => "#CONTENT_VIDEO_IBLOCK_ID#",
        "VIDEO_PROPERTY_URL" => "LINK",
        "SERVICES_IBLOCK_TYPE" => "#CATALOGS_SERVICES_IBLOCK_TYPE#",
        "SERVICES_IBLOCK_ID" => "#CATALOGS_SERVICES_IBLOCK_ID#",
        "SERVICES_PROPERTY_PRICE" => "PRICE",
        "REVIEWS_IBLOCK_TYPE" => "#CATALOGS_PRODUCTS_REVIEWS_IBLOCK_TYPE#",
        "REVIEWS_IBLOCK_ID" => "#CATALOGS_PRODUCTS_REVIEWS_IBLOCK_ID#",
        "REVIEWS_PROPERTY_ELEMENT_ID" => "ELEMENT_ID",
        "MENU_PROPERTY_PICTURE" => "UF_IMAGE_MENU",
        "REVIEWS_USE_CAPTCHA" => "N",
        "MENU_VIEW" => "simple.1",
        "VOTE_MODE" => "rating",
        "QUANTITY_MODE" => "number",
        "USER_CONSENT" => "N",
        "USER_CONSENT_ID" => "0",
        "USER_CONSENT_IS_CHECKED" => "Y",
        "USER_CONSENT_IS_LOADED" => "N",
        "CONSENT_URL" => "#SITE_DIR#company/consent/",
        "SEF_MODE" => "Y",
        "SEF_FOLDER" => "#SITE_DIR#catalog/",
        "SEF_URL_TEMPLATES" => array(
            "sections" => "",
            "section" => "#SECTION_CODE#/",
            "element" => "#SECTION_CODE#/#ELEMENT_ID#/",
            "compare" => "compare.php?action=#ACTION_CODE#",
            "smart_filter" => "#SECTION_ID#/filter/#SMART_FILTER_PATH#/apply/",
        ),
        "AJAX_MODE" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "CACHE_TYPE" => "A",
        "CACHE_TIME" => "36000000",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "Y",
        "USE_MAIN_ELEMENT_SECTION" => "Y",
        "DETAIL_STRICT_SECTION_CHECK" => "Y",
        "SET_LAST_MODIFIED" => "N",
        "SET_TITLE" => "Y",
        "ADD_SECTIONS_CHAIN" => "Y",
        "ADD_ELEMENT_CHAIN" => "Y",
        "USE_FILTER" => "Y",
        "FILTER_NAME" => "arrFilter",
        "FILTER_TYPE" => "vertical",
        "FILTER_TEMPLATE" => "1",
        "FILTER_COLLAPSED" => "N",
        "FILTER_TYPE_F_VIEW" => "default",
        "FILTER_TYPE_G_VIEW" => "default",
        "FILTER_TYPE_G_SIZE" => "default",
        "FILTER_TYPE_A_PRECISION" => "2",
        "ACTION_VARIABLE" => "action",
        "PRODUCT_ID_VARIABLE" => "id",
        "USE_COMPARE" => "Y",
        "COMPARE_NAME" => "compare",
        "COMPARE_FIELD_CODE" => array(),
        "COMPARE_PROPERTY_CODE" => array(
            "PROPERTY_WEIGTH",
            "PROPERTY_DISPLAY",
            "PROPERTY_LENGTH",
            "PROPERTY_SYSTEM_ADDITIONAL",
            "PROPERTY_QUANTITY_OF_STRIPS",
            "PROPERTY_POWER",
            "PROPERTY_SETTINGS",
            "PROPERTY_SCOPE",
            "PROPERTY_PROCREATOR",
            "PROPERTY_SEASON",
            "PROPERTY_SYSTEM_RELATED_SERVICES",
            "PROPERTY_COMPOSITION",
            "PROPERTY_PROPERTY_TEST",
            "PROPERTY_TYPE",
            "PROPERTY_PATTERN",
            "PROPERTY_ENERGY_CONSUMPTION"
        ),
        "COMPARE_OFFERS_FIELD_CODE" => array(),
        "COMPARE_OFFERS_PROPERTY_CODE" => array(
            "OFFERS_SIZE"
        ),
        "COMPARE_ELEMENT_SORT_FIELD" => "sort",
        "COMPARE_ELEMENT_SORT_ORDER" => "asc",
        "PRICE_CODE" => array(
            "BASE"
        ),
        "USE_PRICE_COUNT" => "Y",
        "SHOW_PRICE_COUNT" => "1",
        "PRICE_VAT_INCLUDE" => "Y",
        "PRICE_VAT_SHOW_VALUE" => "N",
        "CONVERT_CURRENCY" => "Y",
        "CURRENCY_ID" => "RUB",
        "BASKET_URL" => "#SITE_DIR#personal/basket/",
        "USE_PRODUCT_QUANTITY" => "N",
        "PRODUCT_QUANTITY_VARIABLE" => "quantity",
        "ADD_PROPERTIES_TO_BASKET" => "Y",
        "PRODUCT_PROPS_VARIABLE" => "prop",
        "PARTIAL_PRODUCT_PROPERTIES" => "N",
        "PRODUCT_PROPERTIES" => array(),
        "OFFERS_CART_PROPERTIES" => array(),
        "SHOW_TOP_ELEMENTS" => "N",
        "SECTION_COUNT_ELEMENTS" => "Y",
        "SECTION_TOP_DEPTH" => "2",
        "SECTIONS_ROOT_SECTION_DESCRIPTION_SHOW" => "Y",
        "SECTIONS_ROOT_SECTION_DESCRIPTION_POSITION" => "top",
        "SECTIONS_ROOT_TEMPLATE" => "tile.1",
        "SECTIONS_ROOT_MENU_SHOW" => "N",
        "SECTIONS_ROOT_BORDERS" => "Y",
        "SECTIONS_ROOT_COLUMNS" => "3",
        "SECTIONS_ROOT_CHILDREN_SHOW" => "Y",
        "SECTIONS_ROOT_CHILDREN_COUNT" => "3",
        "SECTIONS_ROOT_PICTURE_SHOW" => "Y",
        "SECTIONS_ROOT_PICTURE_SIZE" => "large",
        "SECTIONS_ROOT_DESCRIPTION_SHOW" => "Y",
        "SECTIONS_CHILDREN_SECTION_DESCRIPTION_SHOW" => "Y",
        "SECTIONS_CHILDREN_SECTION_DESCRIPTION_POSITION" => "top",
        "SECTIONS_CHILDREN_TEMPLATE" => "tile.1",
        "SECTIONS_CHILDREN_MENU_SHOW" => "Y",
        "SECTIONS_CHILDREN_BORDERS" => "Y",
        "SECTIONS_CHILDREN_COLUMNS" => "3",
        "SECTIONS_CHILDREN_CHILDREN_SHOW" => "Y",
        "SECTIONS_CHILDREN_CHILDREN_COUNT" => "3",
        "SECTIONS_CHILDREN_PICTURE_SHOW" => "Y",
        "SECTIONS_CHILDREN_PICTURE_SIZE" => "large",
        "SECTIONS_CHILDREN_DESCRIPTION_SHOW" => "Y",
        "PAGE_ELEMENT_COUNT" => "30",
        "LINE_ELEMENT_COUNT" => "3",
        "ELEMENT_SORT_FIELD" => "sort",
        "ELEMENT_SORT_ORDER" => "asc",
        "ELEMENT_SORT_FIELD2" => "id",
        "ELEMENT_SORT_ORDER2" => "desc",
        "LIST_PROPERTY_CODE" => array(
            "PROPERTY_WEIGTH",
            "PROPERTY_DISPLAY",
            "PROPERTY_LENGTH",
            "PROPERTY_SYSTEM_ADDITIONAL",
            "PROPERTY_QUANTITY_OF_STRIPS",
            "PROPERTY_POWER",
            "PROPERTY_SETTINGS",
            "PROPERTY_SCOPE",
            "PROPERTY_PROCREATOR",
            "PROPERTY_SEASON",
            "PROPERTY_SYSTEM_RELATED_SERVICES",
            "PROPERTY_COMPOSITION",
            "PROPERTY_PROPERTY_TEST",
            "PROPERTY_TYPE",
            "PROPERTY_PATTERN",
            "PROPERTY_ENERGY_CONSUMPTION"
        ),
        "INCLUDE_SUBSECTIONS" => "Y",
        "LIST_META_KEYWORDS" => "-",
        "LIST_META_DESCRIPTION" => "-",
        "LIST_BROWSER_TITLE" => "-",
        "SECTION_BACKGROUND_IMAGE" => "-",
        "LIST_OFFERS_FIELD_CODE" => array(),
        "LIST_OFFERS_PROPERTY_CODE" => array(
            "OFFERS_SIZE"
        ),
        "LIST_OFFERS_LIMIT" => "0",
        "LIST_SORT_PRICE" => "1",
        "LIST_VIEW" => "text",
        "LIST_TEXT_TEMPLATE" => "text.1",
        "LIST_TEXT_ACTION" => "buy",
        "LIST_TEXT_BORDERS" => "Y",
        "LIST_TEXT_COUNTER_SHOW" => "Y",
        "LIST_TEXT_VOTE_SHOW" => "Y",
        "LIST_TEXT_QUANTITY_SHOW" => "Y",
        "LIST_LIST_TEMPLATE" => "list.1",
        "LIST_LIST_ACTION" => "buy",
        "LIST_LIST_BORDERS" => "Y",
        "LIST_LIST_COUNTER_SHOW" => "Y",
        "LIST_LIST_OFFERS_USE" => "Y",
        "LIST_LIST_VOTE_SHOW" => "Y",
        "LIST_LIST_QUANTITY_SHOW" => "Y",
        "LIST_TILE_TEMPLATE" => "tile.1",
        "LIST_TILE_ACTION" => "buy",
        "LIST_TILE_BORDERS" => "Y",
        "LIST_TILE_COLUMNS" => "3",
        "LIST_TILE_COUNTER_SHOW" => "Y",
        "LIST_TILE_OFFERS_USE" => "Y",
        "LIST_TILE_VOTE_SHOW" => "Y",
        "LIST_TILE_QUANTITY_SHOW" => "Y",
        "QUICK_VIEW_USE" => "Y",
        "QUICK_VIEW_TEMPLATE" => "1",
        "QUICK_VIEW_PROPERTY_CODE" => array(
            "PROPERTY_WEIGTH",
            "PROPERTY_DISPLAY",
            "PROPERTY_LENGTH",
            "PROPERTY_SYSTEM_ADDITIONAL",
            "PROPERTY_QUANTITY_OF_STRIPS",
            "PROPERTY_POWER",
            "PROPERTY_SETTINGS",
            "PROPERTY_SCOPE",
            "PROPERTY_PROCREATOR",
            "PROPERTY_SEASON",
            "PROPERTY_SYSTEM_RELATED_SERVICES",
            "PROPERTY_COMPOSITION",
            "PROPERTY_PROPERTY_TEST",
            "PROPERTY_TYPE",
            "PROPERTY_PATTERN",
            "PROPERTY_ENERGY_CONSUMPTION"
        ),
        "QUICK_VIEW_PROPERTY_DESCRIPTION" => "",
        "QUICK_VIEW_MARKS_SHOW" => "Y",
        "QUICK_VIEW_WEIGHT_SHOW" => "Y",
        "QUICK_VIEW_QUANTITY_SHOW" => "Y",
        "QUICK_VIEW_ACTION" => "buy",
        "QUICK_VIEW_GALLERY_PANEL" => "Y",
        "QUICK_VIEW_GALLERY_PREVIEW" => "Y",
        "QUICK_VIEW_INFORMATION_PAYMENT" => "Y",
        "QUICK_VIEW_INFORMATION_SHIPMENT" => "Y",
        "DETAIL_PROPERTY_CODE" => array(
            "PROPERTY_WEIGTH",
            "PROPERTY_DISPLAY",
            "PROPERTY_LENGTH",
            "PROPERTY_SYSTEM_ADDITIONAL",
            "PROPERTY_QUANTITY_OF_STRIPS",
            "PROPERTY_POWER",
            "PROPERTY_SETTINGS",
            "PROPERTY_SCOPE",
            "PROPERTY_PROCREATOR",
            "PROPERTY_SEASON",
            "PROPERTY_SYSTEM_RELATED_SERVICES",
            "PROPERTY_COMPOSITION",
            "PROPERTY_PROPERTY_TEST",
            "PROPERTY_TYPE",
            "PROPERTY_PATTERN",
            "PROPERTY_ENERGY_CONSUMPTION"
        ),
        "DETAIL_META_KEYWORDS" => "-",
        "DETAIL_META_DESCRIPTION" => "-",
        "DETAIL_BROWSER_TITLE" => "-",
        "DETAIL_SET_CANONICAL_URL" => "N",
        "SECTION_ID_VARIABLE" => "SECTION_ID",
        "DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
        "DETAIL_BACKGROUND_IMAGE" => "-",
        "SHOW_DEACTIVATED" => "N",
        "DETAIL_OFFERS_FIELD_CODE" => array(),
        "DETAIL_OFFERS_PROPERTY_CODE" => array(
            "OFFERS_SIZE"
        ),
        "DETAIL_TEMPLATE" => "default.1",
        "DETAIL_MENU_SHOW" => "N",
        "DETAIL_REVIEWS_SHOW" => "Y",
        "DETAIL_VIEW" => "wide",
        "DETAIL_PANEL_SHOW" => "Y",
        "DETAIL_ACTION" => "buy",
        "DETAIL_VOTE_SHOW" => "Y",
        "DETAIL_QUANTITY_SHOW" => "Y",
        "DETAIL_COUNTER_SHOW" => "Y",
        "DETAIL_STORES_SHOW" => "Y",
        "DETAIL_SETS_SHOW" => "Y",
        "DETAIL_ARTICLE_SHOW" => "Y",
        "DETAIL_BRAND_SHOW" => "Y",
        "DETAIL_GALLERY_SHOW" => "Y",
        "DETAIL_GALLERY_ZOOM" => "Y",
        "DETAIL_GALLERY_POPUP" => "Y",
        "DETAIL_GALLERY_SLIDER" => "Y",
        "DETAIL_SERVICES_SHOW" => "Y",
        "DETAIL_DOCUMENTS_SHOW" => "Y",
        "DETAIL_ASSOCIATED_SHOW" => "Y",
        "DETAIL_RECOMMENDED_SHOW" => "Y",
        "DETAIL_VIDEO_SHOW" => "Y",
        "DETAIL_DESCRIPTION_PREVIEW_SHOW" => "Y",
        "DETAIL_DESCRIPTION_DETAIL_SHOW" => "Y",
        "DETAIL_PROPERTIES_PREVIEW_SHOW" => "Y",
        "DETAIL_PROPERTIES_PREVIEW_COUNT" => "4",
        "DETAIL_PROPERTIES_DETAIL_SHOW" => "Y",
        "DETAIL_PRICE_EXTENDED" => "Y",
        "DETAIL_FORM_SHOW" => "Y",
        "DETAIL_WEB_FORM_ID" => "#FORMS_FEEDBACK_ID#",
        "DETAIL_WEB_FORM_TEMPLATE" => ".default",
        "LINK_IBLOCK_TYPE" => "",
        "LINK_IBLOCK_ID" => "",
        "LINK_PROPERTY_SID" => "",
        "LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
        "USE_ALSO_BUY" => "N",
        "USE_GIFTS_DETAIL" => "N",
        "USE_GIFTS_SECTION" => "N",
        "USE_GIFTS_MAIN_PR_SECTION_LIST" => "N",
        "USE_STORE" => "N",
        "STORES" => array(),
        "USE_MIN_AMOUNT" => "Y",
        "USER_FIELDS" => array(),
        "FIELDS" => array(
            "TITLE",
            "ADDRESS",
            "DESCRIPTION",
            "PHONE",
            "SCHEDULE",
            "EMAIL",
        ),
        "MIN_AMOUNT" => "10",
        "SHOW_EMPTY_STORE" => "Y",
        "SHOW_GENERAL_STORE_INFORMATION" => "N",
        "STORE_PATH" => "#SITE_DIR#contacts/stores/#store_id#",
        "MAIN_TITLE" => "Наличие на складах",
        "OFFERS_SORT_FIELD" => "sort",
        "OFFERS_SORT_ORDER" => "asc",
        "OFFERS_SORT_FIELD2" => "id",
        "OFFERS_SORT_ORDER2" => "desc",
        "PAGER_TEMPLATE" => ".default",
        "DISPLAY_TOP_PAGER" => "N",
        "DISPLAY_BOTTOM_PAGER" => "Y",
        "PAGER_TITLE" => "Товары",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "LAZY_LOAD" => "Y",
        "SET_STATUS_404" => "Y",
        "SHOW_404" => "Y",
        "FILE_404" => "#SITE_DIR#404.php",
        "COMPATIBLE_MODE" => "Y",
        "USE_ELEMENT_COUNTER" => "Y",
        "DISABLE_INIT_JS_IN_COMPONENT" => "Y",
        "DETAIL_SET_VIEWED_IN_COMPONENT" => "Y",
        "FILTER_FIELD_CODE" => array(),
        "FILTER_PROPERTY_CODE" => array(
            "PROPERTY_WEIGTH",
            "PROPERTY_DISPLAY",
            "PROPERTY_LENGTH",
            "PROPERTY_SYSTEM_ADDITIONAL",
            "PROPERTY_QUANTITY_OF_STRIPS",
            "PROPERTY_POWER",
            "PROPERTY_SETTINGS",
            "PROPERTY_SCOPE",
            "PROPERTY_PROCREATOR",
            "PROPERTY_SEASON",
            "PROPERTY_SYSTEM_RELATED_SERVICES",
            "PROPERTY_COMPOSITION",
            "PROPERTY_PROPERTY_TEST",
            "PROPERTY_TYPE",
            "PROPERTY_PATTERN",
            "PROPERTY_ENERGY_CONSUMPTION"
        ),
        "FILTER_PRICE_CODE" => array(
            "BASE"
        ),
        "FILTER_OFFERS_FIELD_CODE" => array(),
        "FILTER_OFFERS_PROPERTY_CODE" => array(
            "OFFERS_SIZE"
        ),
        "USE_REVIEW" => "N",
        "DISPLAY_ELEMENT_SELECT_BOX" => "N",
        "QUICK_VIEW_COUNTER_SHOW" => "Y",
        "QUICK_VIEW_PAYMENT_URL" => "#SITE_DIR#help/buys/payment/",
        "QUICK_VIEW_SHIPMENT_URL" => "#SITE_DIR#help/buys/delivery/",
        "LIST_TILE_BORDERS_STYLE" => "squared",
        "LIST_TILE_MARKS_SHOW" => "Y",
        "LIST_TILE_MARKS_ORIENTATION" => "horizontal",
        "LIST_TILE_NAME_POSITION" => "middle",
        "LIST_TILE_NAME_ALIGN" => "left",
        "LIST_TILE_PRICE_ALIGN" => "left",
        "LIST_TILE_IMAGE_SLIDER_SHOW" => "Y",
        "LIST_TILE_OFFERS_ALIGN" => "start",
        "LIST_TILE_OFFERS_VIEW" => "default",
        "LIST_TILE_VOTE_ALIGN" => "left",
        "LIST_TILE_QUANTITY_ALIGN" => "left",
        "LIST_TILE_WEIGHT_SHOW" => "Y",
        "LIST_TILE_WEIGHT_ALIGN" => "left",
        "LIST_TILE_DESCRIPTION_SHOW" => "Y",
        "LIST_TILE_DESCRIPTION_ALIGN" => "left",
        "LIST_TILE_IMAGE_SLIDER_ANIMATION" => "standard",
        "LIST_TILE_IMAGE_SLIDER_NAV" => "Y",
        "DETAIL_GALLERY_PANEL" => "Y",
        "DETAIL_GALLERY_PREVIEW" => "Y",
        "DETAIL_ADDITIONAL_SHOW" => "Y",
        "DETAIL_TABS_ANIMATION_USE" => "Y",
        "DETAIL_SIZES_SHOW" => "Y",
        "DETAIL_SIZES_PATH" => "#SITE_DIR#include/catalog/sizes.php",
        "DETAIL_SIZES_MODE" => "all",
        "DETAIL_INFORMATION_PAYMENT_SHOW" => "Y",
        "DETAIL_INFORMATION_PAYMENT_PATH" => "#SITE_DIR#include/catalog/information/payment.php",
        "DETAIL_INFORMATION_SHIPMENT_SHOW" => "Y",
        "DETAIL_INFORMATION_SHIPMENT_PATH" => "#SITE_DIR#include/catalog/information/delivery.php",
        "DETAIL_FORM_1_ID" => "#FORMS_CALL_ID#",
        "DETAIL_FORM_2_ID" => "#FORMS_FEEDBACK_ID#",
        "DETAIL_FORM_1_BUTTON_TEXT" => "Позвоните мне",
        "DETAIL_FORM_2_BUTTON_TEXT" => "Задать вопрос",
        "DETAIL_FORM_1_NAME" => "Заказать звонок",
        "DETAIL_FORM_2_NAME" => "Задать вопрос",
        "DETAIL_FORM_TITLE" => "Нужна  консультация?",
        "DETAIL_FORM_DESCRIPTION" => "Сомневаетесь, подойдет ли вам этот товар?",
        "DETAIL_FORM_IMAGE" => "#TEMPLATE_PATH#/images/main-form-temp-3.png",
        "DETAIL_MARKS_SHOW" => "N",
        "DETAIL_DESCRIPTION_SHOW" => "Y",
        "DETAIL_DESCRIPTION_NAME" => "",
        "DETAIL_DESCRIPTION_EXPANDED" => "Y",
        "DETAIL_OFFERS_NAME" => "",
        "DETAIL_OFFERS_EXPANDED" => "Y",
        "DETAIL_PROPERTIES_SHOW" => "Y",
        "DETAIL_PROPERTIES_NAME" => "",
        "DETAIL_PROPERTIES_EXPANDED" => "N",
        "DETAIL_ASSOCIATED_NAME" => "",
        "DETAIL_ASSOCIATED_EXPANDED" => "Y",
        "DETAIL_RECOMMENDED_NAME" => "",
        "DETAIL_RECOMMENDED_EXPANDED" => "Y",
        "VARIABLE_ALIASES" => array(
            "ELEMENT_ID" => "ELEMENT_ID",
            "SECTION_ID" => "SECTION_ID",
        )
    ),
    false
); ?>
<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php") ?>
