<?php

use Sotbit\Origami\Helper\Config, \Bitrix\Main\Localization\Loc;
use Bitrix\Main\Page\Asset;

if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) {
    die();
}

Asset::getInstance()->addCss(SITE_DIR . "local/templates/.default/components/bitrix/news/sotbit_origami_blog/style.css");

\Bitrix\Main\Loader::includeModule('currency');
CJSCore::Init(array('currency'));
$this->setFrameMode(true);

global $arBlogProductsFilter;

$ElementID = $APPLICATION->IncludeComponent(
    "bitrix:news.detail",
    "origami_blog",
    [
        "DISPLAY_DATE"              => $arParams["DISPLAY_DATE"],
        "DISPLAY_NAME"              => $arParams["DISPLAY_NAME"],
        "DISPLAY_PICTURE"           => $arParams["DISPLAY_PICTURE"],
        "DISPLAY_PREVIEW_TEXT"      => $arParams["DISPLAY_PREVIEW_TEXT"],
        "IBLOCK_TYPE"               => $arParams["IBLOCK_TYPE"],
        "IBLOCK_ID"                 => $arParams["IBLOCK_ID"],
        "FIELD_CODE"                => $arParams["DETAIL_FIELD_CODE"],
        "PROPERTY_CODE"             => $arParams["DETAIL_PROPERTY_CODE"],
        "DETAIL_URL"                => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["detail"],
        "SECTION_URL"               => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["section"],
        "META_KEYWORDS"             => $arParams["META_KEYWORDS"],
        "META_DESCRIPTION"          => $arParams["META_DESCRIPTION"],
        "BROWSER_TITLE"             => $arParams["BROWSER_TITLE"],
        "SET_CANONICAL_URL"         => $arParams["DETAIL_SET_CANONICAL_URL"],
        "DISPLAY_PANEL"             => $arParams["DISPLAY_PANEL"],
        "SET_LAST_MODIFIED"         => $arParams["SET_LAST_MODIFIED"],
        "SET_TITLE"                 => $arParams["SET_TITLE"],
        "MESSAGE_404"               => $arParams["MESSAGE_404"],
        "SET_STATUS_404"            => $arParams["SET_STATUS_404"],
        "SHOW_404"                  => $arParams["SHOW_404"],
        "FILE_404"                  => $arParams["FILE_404"],
        "INCLUDE_IBLOCK_INTO_CHAIN" => $arParams["INCLUDE_IBLOCK_INTO_CHAIN"],
        "ADD_SECTIONS_CHAIN"        => $arParams["ADD_SECTIONS_CHAIN"],
        "ACTIVE_DATE_FORMAT"        => $arParams["DETAIL_ACTIVE_DATE_FORMAT"],
        "CACHE_TYPE"                => $arParams["CACHE_TYPE"],
        "CACHE_TIME"                => $arParams["CACHE_TIME"],
        "CACHE_GROUPS"              => $arParams["CACHE_GROUPS"],
        "USE_PERMISSIONS"           => $arParams["USE_PERMISSIONS"],
        "GROUP_PERMISSIONS"         => $arParams["GROUP_PERMISSIONS"],
        "DISPLAY_TOP_PAGER"         => $arParams["DETAIL_DISPLAY_TOP_PAGER"],
        "DISPLAY_BOTTOM_PAGER"      => $arParams["DETAIL_DISPLAY_BOTTOM_PAGER"],
        "PAGER_TITLE"               => $arParams["DETAIL_PAGER_TITLE"],
        "PAGER_SHOW_ALWAYS"         => "N",
        "PAGER_TEMPLATE"            => $arParams["DETAIL_PAGER_TEMPLATE"],
        "PAGER_SHOW_ALL"            => $arParams["DETAIL_PAGER_SHOW_ALL"],
        "CHECK_DATES"               => $arParams["CHECK_DATES"],
        "ELEMENT_ID"                => $arResult["VARIABLES"]["ELEMENT_ID"],
        "ELEMENT_CODE"              => $arResult["VARIABLES"]["ELEMENT_CODE"],
        "SECTION_ID"                => $arResult["VARIABLES"]["SECTION_ID"],
        "SECTION_CODE"              => $arResult["VARIABLES"]["SECTION_CODE"],
        "IBLOCK_URL"                => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["news"],
        "USE_SHARE"                 => $arParams["USE_SHARE"],
        "SHARE_HIDE"                => $arParams["SHARE_HIDE"],
        "SHARE_TEMPLATE"            => $arParams["SHARE_TEMPLATE"],
        "SHARE_HANDLERS"            => $arParams["SHARE_HANDLERS"],
        "SHARE_SHORTEN_URL_LOGIN"   => $arParams["SHARE_SHORTEN_URL_LOGIN"],
        "SHARE_SHORTEN_URL_KEY"     => $arParams["SHARE_SHORTEN_URL_KEY"],
        "ADD_ELEMENT_CHAIN"         => (isset($arParams["ADD_ELEMENT_CHAIN"])
            ? $arParams["ADD_ELEMENT_CHAIN"] : ''),
        'STRICT_SECTION_CHECK'      => (isset($arParams['STRICT_SECTION_CHECK'])
            ? $arParams['STRICT_SECTION_CHECK'] : ''),
    ],
    $component
);

    $APPLICATION->IncludeComponent(
	"sotbit:crosssell.crosssell.list",
	"origami_default",
	array(
		"ACTION_VARIABLE" => "action",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BACKGROUND_IMAGE" => "-",
		"BASKET_URL" => "/personal/basket.php",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"COMPATIBLE_MODE" => "Y",
		"CONVERT_CURRENCY" => "N",
		"CROSSSELL_LIST" => array('e10'),
		"DETAIL_URL" => "",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"DISPLAY_COMPARE" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_NAME" => "arrFilter",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
        "IBLOCK_ID"                 => Config::get("IBLOCK_ID"),
        "IBLOCK_TYPE"               => Config::get("IBLOCK_TYPE"),
		"INCLUDE_SUBSECTIONS" => "Y",
		"LINE_ELEMENT_COUNT" => "4",
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
        "OFFERS_SORT_FIELD"      => "sort",
        "OFFERS_SORT_ORDER"      => "id",
        "OFFERS_SORT_FIELD2"     => "desc",
        "OFFERS_SORT_ORDER2"     => "desc",
        "OFFERS_LIMIT"           => 0,
        'OFFER_TREE_PROPS' => array(
            1 => "PROTSESSOR",
            2 => "OBEM_OPERATICHNOY_PAMYATI",
            3 => "OBEM_PAMYATI",
            4 => "RAZMER",
            5 => "CHASTOTA_PROTSESSORA",
            6 => "TIP_VIDEOKARTY",
            7 => "TSVET",
            8 => "KOLICHESTVO_YADER_PROTSESORA",
            9 => "OBEM_VIDEOPAMYATI",
            10 => "TSVET_1",
            11 => "USTANOVLENNAYA_OS",
            12 => "CML2_MANUFACTURER",
        ),
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Товары",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => \SotbitOrigami::GetComponentPrices(["BASE","OPT","SMALL_OPT"]),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID" => $ElementID,
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(
		),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"SECTION_URL" => "",
		"SEF_MODE" => "N",
		"SET_BROWSER_TITLE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_TABS" => "N",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"COMPONENT_TEMPLATE" => ".default",
		"SECTION_MODE" => "Y",
		"INTERRUPT_MODE" => "N",
		"SECTION_TEMPLATE" => "origami_section",
		"SHOW_SLIDER" => "N",
		"PAGE_ELEMENT_COUNT" => "5",
        "OFFERS_CART_PROPERTIES" => [
            0 => "SIZES_SHOES",
            1 => "SIZES_CLOTHES",
            2 => "COLOR_REF",
        ],
        "OFFERS_FIELD_CODE"      => [
            0 => "NAME",
            1 => "PREVIEW_PICTURE",
            2 => "DETAIL_PICTURE",
            3 => "DETAIL_PAGE_URL",
        ],
        "OFFERS_PROPERTY_CODE"   => [
            1  => "CML2_BAR_CODE",
            2  => "CML2_ARTICLE",
            5  => "CML2_BASE_UNIT",
            7  => "MORE_PHOTO",
            8  => "FILES",
            9  => "CML2_MANUFACTURER",
            10 => "PROTSESSOR",
            11 => "CHASTOTA_PROTSESSORA",
            12 => "KOLICHESTVO_YADER_PROTSESORA",
            13 => "OBEM_OPERATICHNOY_PAMYATI",
            14 => "TIP_VIDEOKARTY",
            15 => "OBEM_VIDEOPAMYATI",
            16 => "USTANOVLENNAYA_OS",
            17 => "OBEM_PAMYATI",
            18 => "RAZMER",
            19 => "TSVET",
            20 => "TSVET_1",
            21 => "VIDEOKARTA",
        ],

        "PRODUCT_DISPLAY_MODE" => "Y",
        'ADD_PICT_PROP'               => "MORE_PHOTO",
        'OFFER_ADD_PICT_PROP'         => "MORE_PHOTO",
        'PRODUCT_SUBSCRIPTION'        => "Y",
        'SHOW_DISCOUNT_PERCENT'       => "Y",
        'SHOW_OLD_PRICE'              => "Y",
        'SHOW_MAX_QUANTITY'           => "Y",
        'USE_VOTE_RATING'             => "Y",
        'COMPARE_PATH'                => Config::get('COMPARE_PAGE'),
        'COMPARE_NAME'                => "CATALOG_COMPARE_LIST",
        'USE_COMPARE_LIST'            => "Y",
        'SECTION_NAME' => Loc::getMessage('SECT_BLOG_BLOCK_NAME')
	),
	false
);

//$intSectionID = $APPLICATION->IncludeComponent(
//    "bitrix:catalog.section",
//    "origami_section",
//    [
//        "IBLOCK_ID"                 => Config::get("IBLOCK_ID"),
//        "IBLOCK_TYPE"               => Config::get("IBLOCK_TYPE"),
//        "ELEMENT_SORT_FIELD"        => "rand",
//        "ELEMENT_SORT_ORDER"        => "id",
//        "ELEMENT_SORT_FIELD2"       => "desc",
//        "ELEMENT_SORT_ORDER2"       => "desc",
//        "PROPERTY_CODE"             => [
//            0   => "CML2_BAR_CODE",
//            1   => "CML2_ARTICLE",
//            6   => "MORE_PHOTO",
//            7   => "FILES",
//            8   => "CML2_MANUFACTURER",
//            9   => "OPERATSIONNAYA_SISTEMA",
//            10  => "TIP_OPTICHESKOGO_PRIVODA",
//            11  => "VYKHOD_HDMI",
//            12  => "KOLLICHESTVO_PROTSESSOROV",
//            13  => "KOLICHESTVO_YADER",
//            14  => "KLAVIATURA",
//            15  => "MYSH",
//            16  => "TSVET_KORPUSA",
//            17  => "BLOK_PITANIYA",
//            18  => "KORPUS",
//            19  => "PROIZVODITEL",
//            20  => "TIP_VIDEOKARTY",
//            21  => "RAZRABOTCHIK_VIDEOKARTY",
//            22  => "PROIZVODITEL_1",
//            23  => "TIP",
//            24  => "EMKOST",
//            25  => "NAZNACHENIE",
//            26  => "FORM_FAKTOR",
//            27  => "INTERFEYS_USB",
//            28  => "IGROVOY",
//            29  => "SKOROST_VRASHCHENIYA",
//            30  => "PODDERZHKA_TRIM",
//            31  => "SHIFROVANIE_DANNYKH",
//            32  => "TIP_FLESH_PAMYATI",
//            33  => "KONTROLLER",
//            34  => "UDAROSTOYKOST_PRI_RABOTE",
//            35  => "UDAROSTOYKOST_PRI_KHRANENII",
//            36  => "VREMYA_NARABOTKI_NA_OTKAZ",
//            37  => "MAKSIMALNAYA_RABOCHAYA_TEMPERATURA",
//            38  => "SUMMARNOE_CHISLO_ZAPISYVAEMYKH_BAYTOV_TBW",
//            39  => "POTREBLYAEMAYA_MOSHCHNOST",
//            40  => "KOLICHESTVO_DISKOV",
//            41  => "PROIZVODITEL_2",
//            42  => "LINEYKA_PROTSESSOROV",
//            43  => "SOCKET",
//            44  => "OBEM_KESHA_L3",
//            45  => "KOLICHESTVO_YADER_1",
//            46  => "CHASTOTA_PROTSESSORA",
//            47  => "YADRO",
//            48  => "IGROVOY_1",
//            49  => "INTEGRIROVANNOE_GRAFICHESKOE_YADRO",
//            50  => "KOMPLEKTATSIYA",
//            51  => "TEKHPROTSESS",
//            52  => "OBEM_KESHA_L1",
//            53  => "OBEM_KESHA_L2",
//            54  => "PODDERZHKA_HT",
//            55  => "PODDERZHKA_AMD64_EM64T",
//            56  => "PROIZVODITEL_NOUTBUKA",
//            57  => "PROIZVODITEL_3",
//            58  => "KAMERA",
//            59  => "MAKSIMALNOE_VREMYA_POLETA",
//            60  => "TIP_MULTIKOPTERA",
//            61  => "MAKSIMALNAYA_SKOROST_NABORA_VYSOTY",
//            62  => "MAKSIMALNAYA_SKOROST_SNIZHENIYA",
//            63  => "MAKSIMALNAYA_SKOROST_POLETA",
//            64  => "VSTROENNYE_DATCHIKI",
//            65  => "BESKOLLEKTORNYY_DVIGATEL",
//            66  => "PROFESSIONALNAYA_MODEL",
//            67  => "TIP_UPRAVLENIYA",
//            68  => "AVTOPILOT",
//            69  => "VOZVRASHCHENIE_V_TOCHKU_VZLETA",
//            70  => "PODDERZHKA_MOBILNYKH_OS",
//            71  => "VID_OT_PERVOGO_LITSA_FPV",
//            72  => "AKKUMULYATOR",
//            73  => "HEADLESS_MODE",
//            74  => "SLEDOVANIE_ZA_OPERATOROM",
//            75  => "UGOL_OBZORA_KAMERY",
//            76  => "RAZRESHENIE_VIDEOSEMKI",
//            77  => "RAZRESHENIE_FOTOSEMKI",
//            78  => "VIDEOVYKHOD_NA_PULTE_UPRAVLENIYA",
//            79  => "DALNOST_UPRAVLENIYA",
//            80  => "UPRAVLENIE_ZHESTAMI",
//            81  => "PROIZVODITEL_4",
//            82  => "SOCKET_1",
//            83  => "FORM_FAKTOR_1",
//            84  => "IGROVAYA",
//            85  => "TIP_PAMYATI",
//            86  => "NAZVANIE_CHIPSETA",
//            87  => "KOLICHESTVO_SLOTOV_PAMYATI",
//            88  => "RAZEM_HDMI_NA_ZADNEY_PANELI",
//            89  => "PODDERZHIVAEMYE_PROTSESSORY",
//            90  => "PODDERZHKA_MNOGOYADERNYKH_PROTSESSOROV",
//            91  => "BIOS",
//            92  => "PODDERZHKA_EFI",
//            93  => "PODDERZHKA_SLI_CROSSFIRE",
//            94  => "PAMYAT",
//            95  => "PODDERZHKA_DVUKHKANALNOGO_REZHIMA",
//            96  => "MAKSIMALNYY_OBEM_PAMYATI",
//            97  => "SATA",
//            98  => "KOLICHESTVO_SLOTOV_M_2",
//            99  => "TIP_INTERFEYSA_M_2",
//            100 => "TIP_SLOTOV_M_2",
//            101 => "SLOTY_RASSHIRENIYA",
//            102 => "ETHERNET",
//            103 => "ZVUK",
//            104 => "PODDERZHKA_PCI_EXPRESS_2_0",
//            105 => "PODDERZHKA_PCI_EXPRESS_3_0",
//            106 => "RAZEMY_NA_ZADNEY_PANELI",
//            107 => "OSNOVNOY_RAZEM_PITANIYA",
//            108 => "RAZEM_PITANIYA_PROTSESSORA",
//            109 => "TIP_SISTEMY_OKHLAZHDENIYA",
//            110 => "KOMPLEKTATSIYA_1",
//            111 => "RAZEM_PODKLYUCHENIYA_LENTY_RGB",
//            112 => "IGROVOY_2",
//            113 => "NAZNACHENIE_1",
//            114 => "VODYANOE_OKHLAZHDENIE",
//            115 => "SOCKET_2",
//            116 => "SOVMESTIMOST",
//            117 => "MATERIAL_RADIATORA",
//            118 => "RAZMERY_RADIATORA_SHKHVXG",
//            119 => "KOLICHESTVO_VENTILYATOROV",
//            120 => "RAZMERY_VENTILYATORA_DKHSHKHV",
//            121 => "SKOROST_VRASHCHENIYA_1",
//            122 => "UROVEN_SHUMA",
//            123 => "TIP_KONNEKTORA",
//            124 => "TSVET_PODSVETKI",
//            125 => "REGULYATOR_OBOROTOV",
//            126 => "VREMYA_BEZOTKAZNOY_RABOTY",
//            127 => "SROK_SLUZHBY_PODSHIPNIKA_POMPY",
//            128 => "RAZMERY_POMPY",
//            129 => "VOZDUSHNYY_POTOK",
//            130 => "TIP_PODSHIPNIKA",
//            131 => "KOLICHESTVO_TEPLOVYKH_TRUBOK",
//            132 => "DOPOLNITELNAYA_INFORMATSIYA",
//            133 => "PROIZVODITEL_5",
//            134 => "INTERFEYS",
//            135 => "ZASHCHITA_PAROLEM",
//            136 => "APPARATNOE_SHIFROVANIE_DANNYKH",
//            137 => "REZERVNOE_KOPIROVANIE_DANNYKH",
//            138 => "VYDVIZHNOY_RAZEM",
//            139 => "VODONEPRONITSAEMYY_KORPUS",
//            140 => "MATERIAL_KORPUSA",
//            141 => "PROIZVODITEL_6",
//            142 => "TIP_USTROYSTVA",
//            143 => "IGROVAYA_1",
//            144 => "BESPROVODNAYA",
//            145 => "INTERFEYS_PODKLYUCHENIYA",
//            146 => "PREDNAZNACHENIE",
//            147 => "RAZRESHENIE_OPTICHESKOGO_SENSORA",
//            148 => "DIZAYN",
//            149 => "TIP_BESPROVODNOY_SVYAZI",
//            150 => "PRINTSIP_RABOTY",
//            151 => "TIP_RUKAVA",
//            152 => "POKROY",
//            153 => "KONSTRUKTIVNYE_ELEMENTY",
//            154 => "OSOBENNOSTI_TKANI",
//            155 => "MATERIAL_PODKLADKI",
//            156 => "STRANA_BRENDA",
//            157 => "STRANA_PROIZVODITEL",
//            158 => "KOMPLEKTATSIYA_2",
//            159 => "SOSTAV",
//            160 => "DEKORATIVNYE_ELEMENTY",
//            161 => "STIL",
//            162 => "RASPRODAZHA",
//            163 => "KOSTYUM_PO_TIPU",
//            164 => "VYSOTA_KABLUKA",
//            165 => "VYSOTA_PLATFORMY",
//            166 => "GOLENISHCHE",
//            167 => "MATERIAL_STELKI",
//            168 => "FORMA_KABLUKA",
//            169 => "OSOBENNOST_MATERIALA_VERKHA",
//            170 => "FORMA_MYSKA",
//            171 => "MATERIAL_PODOSHVY",
//            172 => "MATERIAL_VERKHA",
//            173 => "PO_NAZNACHENIYU",
//            174 => "RISUNOK",
//            175 => "REMNI",
//            176 => "OSOBENNOSTI",
//            177 => "PRYAZHKA",
//            178 => "MEKHANIZM",
//            179 => "MATERIAL_BRASLETA",
//            180 => "MATERIAL_KORPUSA_1",
//            181 => "FORMA_KORPUSA",
//            182 => "STEKLO",
//            183 => "TSIFERBLAT",
//            184 => "TIP_INDIKATSII",
//            185 => "TIP_KREPLENIYA",
//            186 => "CHASY",
//            187 => "DIAGONAL_EKRANA",
//            188 => "RAZRESHENIE_EKRANA",
//            189 => "TIP_ZHESTKOGO_DISKA",
//            190 => "TIP_1",
//            191 => "TIP_PAMYATI_1",
//            192 => "CHASTOTA_PAMYATI",
//            193 => "SHIROKOFORMATNYY_EKRAN",
//            194 => "SENSORNYY_EKRAN",
//            195 => "MULTITACH_EKRAN",
//            196 => "SVETODIODNAYA_PODSVETKA_EKRANA",
//            197 => "TIP_SIM_KARTY",
//            198 => "FONARIK",
//            199 => "KONSTRUKTSIYA",
//            200 => "VERSIYA_OS",
//            201 => "TIP_2",
//            202 => "TIP_KORPUSA",
//            203 => "KOLICHESTVO_SIM_KART",
//            204 => "REZHIM_RABOTY_NESKOLKIKH_SIM_KART",
//            205 => "RAZMERY_SHXVXT",
//            206 => "DIAGONAL_EKRANA_1",
//            207 => "TIP_EKRANA",
//            208 => "TIP_SENSORNOGO_EKRANA",
//            209 => "SILA_NAZHATIYA_NA_EKRAN",
//            210 => "RAZMER_IZOBRAZHENIYA",
//            211 => "CHISLO_PIKSELEY_NA_DYUYM_PPI",
//            212 => "SOOTNOSHENIE_STORON",
//            213 => "AVTOMATICHESKIY_POVOROT_EKRANA",
//            214 => "USTOYCHIVOE_K_TSARAPINAM_STEKLO",
//            215 => "TYLOVAYA_FOTOKAMERA",
//            216 => "FOTOVSPYSHKA",
//            217 => "FUNKTSII_TYLOVOY_FOTOKAMERY",
//            218 => "DIAFRAGMA_TYLOVOY_FOTOKAMERY",
//            219 => "ZAPIS_VIDEOROLIKOV",
//            220 => "FRONTALNAYA_KAMERA",
//            221 => "AUDIO",
//            222 => "RAZEM_DLYA_NAUSHNIKOV",
//            223 => "STANDART_SVYAZI",
//            224 => "INTERFEYSY_SVYAZI",
//            225 => "SPUTNIKOVAYA_NAVIGATSIYA",
//            226 => "CISTEMA_A_GPS",
//            227 => "PROTSESSOR",
//            228 => "PODDERZHKA_DIAPAZONOV_LTE",
//            229 => "KOLICHESTVO_YADER_PROTSESSORA",
//            230 => "VIDEOPROTSESSOR",
//            231 => "OBEM_VSTROENNOY_PAMYATI",
//            232 => "OBEM_OPERATIVNOY_PAMYATI",
//            233 => "SLOT_DLYA_KART_PAMYATI",
//            234 => "EMKOST_AKKUMULYATORA",
//            235 => "MAKS_RAZRESHENIE_VIDEO",
//            236 => "MAKS_CHASTOTA_KADROV_VIDEO",
//            237 => "GEO_TAGGING",
//            238 => "VREMYA_RABOTY_V_REZHIME_RAZGOVORA",
//            239 => "VREMYA_RABOTY_V_REZHIME_OZHIDANIYA",
//            240 => "VREMYA_RABOTY_V_REZHIME_PROSLUSHIVANIYA_MUZYKI",
//            241 => "TIP_RAZEMA_DLYA_ZARYADKI",
//            242 => "FUNKTSIYA_BYSTROY_ZARYADKI",
//            243 => "GROMKAYA_SVYAZ",
//            244 => "REZHIM_POLETA",
//            245 => "USB_HOST",
//            246 => "OSOBENNOSTI_1",
//            247 => "KOMPLEKTATSIYA_3",
//            248 => "DATCHIKI",
//            249 => "UPRAVLENIE",
//            250 => "KONSTRUKTSIYA_AKKUMULYATOR",
//            251 => "TIP_AKKUMULYATORA",
//            252 => "PROFIL_A2DP",
//            253 => "PROIZVODITEL_7",
//            254 => "TIP_3",
//            255 => "BESPROVODNOE",
//            256 => "BYSTRAYA_ZARYADKA",
//            257 => "MAKS_VYKHODNOY_TOK",
//            258 => "DLINA_USTROYSTVA",
//            259 => "RAZEM_PODKLYUCHENIYA",
//            260 => "KOLICHESTVO_RAZEMOV",
//            261 => "KABEL_V_KOMPLEKTE",
//            262 => "TIP_NOSITELYA",
//            263 => "PODDERZHKA_VIDEO_VYSOKOGO_RAZRESHENIYA",
//            264 => "MAKSIMALNOE_RAZRESHENIE_VIDEOSEMKI",
//            265 => "SHIROKOFORMATNYY_REZHIM_VIDEO",
//            266 => "REZHIM_NOCHNOY_SEMKI",
//            267 => "OBEM_VSTROENNOY_FLESH_PAMYATI",
//            268 => "TIP_MATRITSY",
//            269 => "KOLICHESTVO_MATRITS",
//            270 => "MATRITSA",
//            271 => "FIZICHESKIY_RAZMER_MATRITSY",
//            272 => "FOKUSNOE_RASSTOYANIE_OBEKTIVA",
//            273 => "RUCHNAYA_USTANOVKA_EKSPOZITSII",
//            274 => "EKVIVALENTNOE_FOKUSNOE_RASSTOYANIE",
//            275 => "ZOOM_OPTICHESKIY",
//            276 => "ZOOM_TSIFROVOY",
//            277 => "DIAFRAGMA",
//            278 => "DIAMETR_FILTRA",
//            279 => "RUCHNAYA_FOKUSIROVKA",
//            280 => "ZHK_EKRAN",
//            281 => "FORMATY_ZAPISI",
//            282 => "STABILIZATOR_IZOBRAZHENIYA",
//            283 => "SENSORNYY_DISPLEY",
//            284 => "VIDOISKATEL",
//            285 => "BALANS_BELOGO",
//            286 => "DOPOLNITELNYE_VOZMOZHNOSTI",
//            287 => "PODDERZHKA_KART_PAMYATI",
//            288 => "MINIMALNAYA_OSVESHCHENNOST",
//            289 => "SHIROKOFORMATNYY_REZHIM_FOTO",
//            290 => "TIP_4",
//            291 => "PODDERZHKA_HD_HIGH_DEFINITION",
//            292 => "PODDERZHKA_3D",
//            293 => "ZHESTKIY_DISK",
//            294 => "TIP_PROTSESSORA",
//            295 => "PROIZVODITELNOST_SISTEMY_PRI_VYCHISLENIYAKH_S_PLAV",
//            296 => "GRAFICHESKIY_PROTSESSOR",
//            297 => "OPERATIVNAYA_PAMYAT",
//            298 => "RAZEMY",
//            299 => "KOMMUNIKATSII",
//            300 => "PROIGRYVANIE_VIDEO",
//            301 => "PODDERZHIVAEMYE_NOSITELI",
//            302 => "PODDERZHIVAEMYE_FORMATY",
//            303 => "KONTROLLER_V_KOMPLEKTE",
//            304 => "AKSESSUARY_V_KOMPLEKTE",
//            305 => "TIP_NOSITELYA_DLYA_IGR",
//            306 => "SOVMESTIMOST_S_IGRAMI_DLYA_PRISTAVOK",
//            307 => "OSOBENNOSTI_2",
//            308 => "PODDERZHKA_4K_UHD",
//            309 => "OBEM_VSTROENNOY_FLESH_PAMYATI_1",
//            310 => "USTROYSTVO_DLYA_CHTENIYA_KART_PAMYATI",
//            311 => "ISTOCHNIK_PITANIYA",
//            312 => "VSTROENNYY_DINAMIK",
//            313 => "VSTROENNYY_MIKROFON",
//            314 => "SENSORNYY_EKRAN_1",
//            315 => "TIP_AKSESSUARA",
//            316 => "VOZRASTNYE_OGRANICHENIYA",
//            317 => "IZ_CHEGO_SDELANO_SOSTAV",
//            318 => "SOVMESTIMOST_1",
//            319 => "INTERFEYS_1",
//            320 => "PROIZVODITEL_8",
//            321 => "MODEL",
//            322 => "TIP_NAUSHNIKOV",
//            323 => "KREPLENIE_MIKROFONA",
//            324 => "REGULYATOR_GROMKOSTI",
//            325 => "NOMINAL",
//            326 => "SROK_PODPISKI",
//            327 => "TIP_AKTIVATSII",
//            328 => "PROIZVODITEL_9",
//            329 => "DIAGONAL_EKRANA_2",
//            330 => "RAZRESHENIE_EKRANA_1",
//            331 => "PROTSESSOR_1",
//            332 => "RAZMER_OPERATIVNOY_PAMYATI",
//            333 => "VIDEOPROTSESSOR_1",
//            334 => "TVERDOTELNYY_NAKOPITEL_SSD",
//            335 => "OPERATSIONNAYA_SISTEMA_1",
//            336 => "PROIZVODITEL_10",
//            337 => "IGROVOY_KOMPYUTER",
//            338 => "LINEYKA_PROTSESSORA",
//            339 => "CHASTOTA_PROTSESSORA_1",
//            340 => "RAZMER_OPERATIVNOY_PAMYATI_1",
//            341 => "TIP_PAMYATI_2",
//            342 => "VIDEOKARTA",
//            343 => "TIP_VIDEOKARTY_1",
//            344 => "OBEM_VIDEOPAMYATI",
//            345 => "OBEM_ZHESTKOGO_DISKA",
//            346 => "TVERDOTELNYY_DISK_SSD",
//            347 => "RADIUS_DEYSTVIYA_BESPROVODNOY_SVYAZI",
//            348 => "KOLESO_PROKRUTKI",
//            349 => "CHASTOTA_OPROSA",
//            350 => "SENSORNAYA_PROKRUTKA",
//            351 => "KOLICHESTVO_KLAVISH",
//            352 => "KOLICHESTVO_PROGRAMMIRUEMYKH_KLAVISH",
//            353 => "DLINA_PROVODA",
//            354 => "ISTOCHNIK_PITANIYA_1",
//            355 => "PROIZVODITEL_11",
//            356 => "IGROVAYA_2",
//            357 => "INTERFEYS_PODKLYUCHENIYA_1",
//            358 => "BESPROVRODNAYA_KLAVIATURA",
//            359 => "PREDNAZNACHENIE_1",
//            360 => "TIP_BESPROVODNOY_SVYAZI_1",
//            361 => "TIP_KLAVIATURY",
//            362 => "PODSVETKA_KLAVISH",
//            363 => "KONSTRUKTSIYA_1",
//            364 => "TSIFROVOY_BLOK",
//            365 => "RASKLADKA_DLYA_USTROYTVA_APPLE",
//            366 => "KOLICHESTVO_DOPOLNITELNYKH_KLAVISH",
//            367 => "ISTOCHNIK_PITANIYA_2",
//            368 => "TONKAYA_KLAVIATURA",
//            369 => "OSTROVNAYA_KLAVIATURA",
//            370 => "OBSHCHEE_KOLICHESTVO_KLAVISH",
//            371 => "TACHPAD",
//            372 => "NALICHIE_REGULYATORA_GROMKOSTI",
//            373 => "PROIZVODITEL_12",
//            374 => "TIP_5",
//            375 => "MAKSIMALNYY_RAZMER_EKRANA",
//            376 => "ZHENSKAYA",
//            377 => "MATERIAL",
//            378 => "ZASHCHITA_OT_VODY",
//            379 => "ANTIVOR",
//            380 => "VNESHNEE_OTDELENIE",
//            381 => "OTDELENIE_ORGANAYZER",
//            382 => "KARMAN_DLYA_TELEFONA",
//            383 => "PLECHEVOY_REMEN",
//            384 => "PROIZVODITEL_13",
//            385 => "TIP_USTROYSTVA_1",
//            386 => "KONSTRUKTSIYA_2",
//            387 => "TIP_BESPROVODNOGO_SOEDINENIYA",
//            388 => "MIKROFON",
//            389 => "SISTEMA_AKTIVNOGO_SHUMOPODAVLENIYA",
//            390 => "TEKHNOLOGIYA",
//            391 => "OTSOEDINYAEMYY_KABEL",
//            392 => "MINIMALNAYA_VOSPROIZVODIMAYA_CHASTOTA",
//            393 => "SPORTIVNYE",
//            394 => "MAKSIMALNAYA_VOSPROIZVODIMAYA_CHASTOTA",
//            395 => "IMPEDANS",
//            396 => "CHUVSTVITELNOST",
//            397 => "MAKSIMALNAYA_MOSHCHNOST",
//            398 => "TIP_AKUSTICHESKOGO_OFORMLENIYA",
//            399 => "TIP_KREPLENIYA_1",
//            400 => "DIAMETR_MEMBRANY",
//            401 => "KOLICHESTVO_DRAYVEROV",
//            402 => "SKLADNAYA_KONSTRUKTSIYA",
//            403 => "PODKLYUCHENIE_KABELYA",
//            404 => "TIP_KABELYA",
//            405 => "ZASHCHITA_OT_VODY_1",
//            406 => "SVETODIODNYY_INDIKATOR",
//            407 => "RAZEM",
//            408 => "MOROZILNAYA_KAMERA",
//            409 => "MATERIAL_POKRYTIYA",
//            410 => "UPRAVLENIE_1",
//            411 => "ENERGOPOTREBLENIE",
//            412 => "KOLICHESTVO_KOMPRESSOROV",
//            413 => "KHLADAGENT",
//            414 => "KOLICHESTVO_KAMER",
//            415 => "KOLICHESTVO_DVEREY",
//            416 => "RAZMORAZHIVANIE_MOROZILNOY_KAMERY",
//            417 => "RAZMORAZHIVANIE_KHOLODILNOY_KAMERY",
//            418 => "AVTONOMNOE_SOKHRANENIE_KHOLODA",
//            419 => "MOSHCHNOST_ZAMORAZHIVANIYA",
//            420 => "DOPOLNITELNYE_VOZMOZHNOSTI_1",
//            421 => "OBSHCHIY_OBEM",
//            422 => "OBEM_KHOLODILNOY_KAMERY",
//            423 => "OBEM_MOROZILNOY_KAMERY",
//            424 => "DISPLEY",
//            425 => "GENERATOR_LDA",
//            426 => "MATERIAL_POLOK",
//            427 => "VOZMOZHNOST_PEREVESHIVANIYA_DVERI",
//            428 => "UROVEN_SHUMA_1",
//            429 => "KLIMATICHESKIY_KLASS",
//            430 => "PROIZVODITEL_14",
//            431 => "VAROCHNAYA_PANEL",
//            432 => "DUKHOVKA",
//            433 => "UPRAVLENIE_2",
//            434 => "CHASY_1",
//            435 => "NOMINALNAYA_POTREBLYAEMAYA_MOSHCHNOST",
//            436 => "RABOCHAYA_POVERKHNOST",
//            437 => "CHISLO_ELEKTRICHESKIKH_KOMFOROK",
//            438 => "KOLICHESTVO_KONFOROK",
//            439 => "INDIKATORY_OSTATOCHNOGO_TEPLA",
//            440 => "ZASHCHITNOE_OTKLYUCHENIE",
//            441 => "OBEM_DUKHOVKI",
//            442 => "DVERTSA",
//            443 => "KONVEKTSIYA",
//            444 => "OSOBENNOSTI_DUKHOVKI",
//            445 => "TIP_DUKHOVKI",
//            446 => "GRIL",
//            447 => "TIP_6",
//            448 => "KLASS_ENERGOPOTREBLENIYA",
//            449 => "ZASHCHITA_OT_PROTECHEK",
//            450 => "KLASS_SUSHKI",
//            451 => "KLASS_MOYKI",
//            452 => "VMESTIMOST_KOMPLEKTOV",
//            453 => "INTENSIVNAYA_MOYKA",
//            454 => "DISPLEY_1",
//            455 => "EKONOMICHNAYA_PROGRAMMA",
//            456 => "ZASHCHITA_OT_DETEY",
//            457 => "TIP_UPRAVLENIYA_1",
//            458 => "TIP_SUSHKI",
//            459 => "REZHIM_POLOVINNOY_ZAGRUZKI",
//            460 => "TAYMER_OTSROCHKI_ZAPUSKA",
//            461 => "DELIKATNAYA_MOYKA",
//            462 => "STANDARTNAYA_PROGRAMMA",
//            463 => "RASKHOD_VODY",
//            464 => "DERZHATEL_DLYA_BOKALOV",
//            465 => "PROIZVODITEL_15",
//            466 => "TIP_7",
//            467 => "TIP_ISPOLZUEMOGO_KOFE",
//            468 => "KAPUCHINATOR",
//            469 => "PRIGOTOVLENIE_ESPRESSO",
//            470 => "MOSHCHNOST",
//            471 => "VSTROENNAYA_KOFEMOLKA",
//            472 => "KONTROL_KREPOSTI_KOFE",
//            473 => "KOLICHESTVO_GRUPP",
//            474 => "TIP_KAPSUL",
//            475 => "OBEM",
//            476 => "TIP_NAGREVATELYA",
//            477 => "REGULIROVKA_STEPENI_POMOLA",
//            478 => "PODOGREV_CHASHEK",
//            479 => "DISPLEY_2",
//            480 => "MATERIAL_KORPUSA_2",
//            481 => "TIP_INSTRUMENTA",
//            482 => "TIP_PATRONA",
//            483 => "KOLICHESTVO_SKOROSTEY_RABOTY",
//            484 => "PITANIE",
//            485 => "DIAMETR_PATRONA",
//            486 => "MAKS_CHISLO_OBOROTOV_KHOLOSTOGO_KHODA",
//            487 => "MAKSIMALNYY_KRUTYASHCHIY_MOMENT",
//            488 => "MAKS_DIAMETR_SVERLENIYA_DEREVO",
//            489 => "MAKS_DIAMETR_SVERLENIYA_METALL",
//            490 => "VOZMOZHNOSTI",
//            491 => "TIP_AKKUMULYATORA_1",
//            492 => "EMKOST_AKKUMULYATORA_1",
//            493 => "NAPRYAZHENIE_AKKUMULYATORA",
//            494 => "SEMNYY_AKKUMULYATOR",
//            495 => "PRISPOSOBLENIYA",
//            496 => "KOMPLEKTATSIYA_4",
//            497 => "KOLICHESTVO_PREDMETOV_V_NABORE",
//            498 => "KOLICHESTVO_BIT_V_KOMPLEKTE",
//            499 => "KLYUCHI_SHESTIGRANNYE",
//            500 => "KOLICHESTVO_TORTSEVYKH_GOLOVOK_V_KOMPLEKTE",
//            501 => "RAZMER_TORTSEVYKH_GOLOVOK",
//            502 => "TIP_KREPLENIYA_BURA_SVERLA",
//            503 => "POTREBLYAEMAYA_MOSHCHNOST_1",
//            504 => "MAKS_CHASTOTA_UDAROV",
//            505 => "MAKS_ENERGIYA_UDARA",
//            506 => "MAKS_DIAMETR_SVERLENIYA_BETON",
//            507 => "MAKS_DIAMETR_SVERLENIYA_POLOY_KORONKOY",
//            508 => "REZHIMY_RABOTY",
//            509 => "SHURUPOVERT",
//            510 => "TSVET_LUCHA",
//            511 => "KOLICHESTVO_LUCHEY",
//            512 => "UGOL_SAMOVYRAVNIVANIYA",
//            513 => "RABOCHAYA_TEMPERATURA",
//            514 => "REZBA",
//            515 => "TOCHNOST",
//            516 => "KLASS_LAZERA",
//            517 => "KOLICHESTVO_ELEMENTOV_PITANIYA",
//            518 => "VREMYA_RABOTY_NA_ODNOM_ZARYADE",
//            519 => "TIP_OBOEV",
//            520 => "OSNOVA_OBOEV",
//            521 => "TEMATIKA_OBOEV",
//            522 => "NAZNACHENIE_2",
//            523 => "KOLLEKTSIYA",
//            524 => "KLASS_IZNOSOSTOYKOSTI",
//            525 => "VLAGOSTOYKOST",
//            526 => "TOLSHCHINA_DOSKI",
//            527 => "FASKA",
//            528 => "TIP_RISUNKA",
//            529 => "RAZMER_PANELI",
//            530 => "TIP_ZAMKA",
//            531 => "KOLICHESTVO_DOSOK_V_UPAKOVKE",
//            532 => "PLOSHCHAD_UPAKOVKI",
//            533 => "OBEM_1",
//            534 => "RAZBAVITEL",
//            535 => "STEPEN_GLYANTSA",
//            536 => "VREMYA_VYSYKHANIYA",
//            537 => "SEZON",
//            538 => "POL",
//            539 => "VID_ZASTEZHKI",
//            540 => "VOROTNIK",
//            541 => "DLINA_RUKAVA",
//            542 => "FAKTURA_MATERIALA",
//            543 => "KOLICHESTVO_PUGOVITS",
//            544 => "TIP_KARMANOV",
//            545 => "GABARITY_PREDMETOV",
//            546 => "SHIRINA_RUKAVA",
//            547 => "OPTICHESKIY_PRIVOD",
//            548 => "SLOT_EXPRESSCARD",
//            549 => "WI_FI",
//            550 => "STANDART_WI_FI",
//            551 => "BLUETOOTH",
//            552 => "VERSIYA_BLUETOOTH",
//            553 => "VSTROENNAYA_SETEVAYA_KARTA",
//            554 => "KOLICHESTVO_INTERFEYSOV_USB_3_0_TYPE_A",
//            555 => "INTERFEYS_USB_3_0_TYPE_C",
//            556 => "VYKHOD_HDMI_1",
//            557 => "VYKHOD_MINI_DISPLAYPORT",
//            558 => "VKHOD_MIKROFONNYY",
//            559 => "VYKHOD_AUDIO_NAUSHNIKI",
//            560 => "VKHOD_MIKROFONNYY_VYKHOD_NA_NAUSHNIKI_COMBO",
//            561 => "VREMYA_RABOTY",
//            562 => "USTROYSTVA_POZITSIONIROVANIYA",
//            563 => "PODSVETKA_KLAVIATURY",
//            564 => "SENSORNAYA_PANEL_TOUCH_BAR",
//            565 => "NALICHIE_KOLONOK",
//            566 => "NALICHIE_SABVUFERA",
//            567 => "NALICHIE_MIKROFONA",
//            568 => "VEB_KAMERA",
//            569 => "RAZRESHENIE_VEB_KAMERY",
//            570 => "SKANER_OTPECHATKA_PALTSA",
//            571 => "SLOT_DLYA_ZAMKA_KENSINGTON",
//            572 => "METALLICHESKIY_KORPUS",
//            573 => "PASSIVNOE_OKHLAZHDENIE",
//            574 => "PROIZVODITEL_16",
//            575 => "PROIZVODITEL_TELEFONA",
//            576 => "MODELI_TELEFONA",
//            577 => "MATERIAL_1",
//            578 => "TIP_8",
//            579 => "PROZRACHNYY",
//            580 => "TIP_KAMERY",
//            581 => "VOZMOZHNOST_SMENY_OBEKTIVA",
//            582 => "OBEKTIV_V_KOMPLEKTE",
//            583 => "FOKUSNOE_RASSTOYANIE_35_MM_EKVIVALENT",
//            584 => "OPTICHESKIY_ZOOM",
//            585 => "DIAFRAGMA_1",
//            586 => "CHISLO_OPTICHESKIKH_ELEMENTOV",
//            587 => "CHISLO_GRUPP_OPTICHESKIKH_ELEMENTOV",
//            588 => "OSOBENNOSTI_3",
//            589 => "OBSHCHEE_CHISLO_PIKSELOV",
//            590 => "CHISLO_EFFEKTIVNYKH_PIKSELOV",
//            591 => "RAZMER",
//            592 => "KROP_FAKTOR",
//            593 => "MAKSIMALNOE_RAZRESHENIE",
//            594 => "TIP_MATRITSY_1",
//            595 => "CHUVSTVITELNOST_1",
//            596 => "RASSHIRENNYE_ZNACHENIYA_ISO",
//            597 => "BALANS_BELOGO_1",
//            598 => "VSPYSHKA",
//            599 => "STABILIZATOR_IZOBRAZHENIYA_FOTOSEMKA",
//            600 => "MAKROSYEMKA",
//            601 => "SKOROST_SEMKI",
//            602 => "TAYMER",
//            603 => "VREMYA_RABOTY_TAYMERA",
//            604 => "FORMAT_KADRA_FOTOSEMKA",
//            605 => "VIDOISKATEL_1",
//            606 => "ISPOLZOVANIE_EKRANA_V_KACHESTVE_VIDOISKATELYA",
//            607 => "ZHK_EKRAN_1",
//            608 => "RUCHNAYA_NASTROYKA_VYDERZHKI_I_DIAFRAGMY",
//            609 => "EKSPOKORREKTSIYA",
//            610 => "ZAMER_EKSPOZITSII",
//            611 => "TIP_AVTOFOKUSA",
//            612 => "KOLICHESTVO_TOCHEK_FOKUSIROVKI",
//            613 => "PODSVETKA_AVTOFOKUSA",
//            614 => "FOKUSIROVKA_PO_LITSU",
//            615 => "TIP_KART_PAMYATI",
//            616 => "FORMATY_IZOBRAZHENIYA",
//            617 => "INTERFEYSY",
//            618 => "FORMAT_AKKUMULYATOROV",
//            619 => "KOLICHESTVO_AKKUMULYATOROV",
//            620 => "EMKOST_AKKUMULYATORA_2",
//            621 => "ZAPIS_VIDEO",
//            622 => "FORMAT_ZAPISI_VIDEO",
//            623 => "VIDEOKODEKI",
//            624 => "MAKSIMALNOE_RAZRESHENIE_ROLIKOV",
//            625 => "MAKSIMALNAYA_CHASTOTA_KADROV_VIDEOROLIKA",
//            626 => "MAKSIMALNAYA_CHASTOTA_KADROV_PRI_SEMKE_HD_VIDEO",
//            627 => "VREMYA_ZAPISI_VIDEO",
//            628 => "ZAPIS_ZVUKA",
//            629 => "TSIFROVOY_ZOOM",
//            630 => "DOPOLNITELNYE_VOZMOZHNOSTI_2",
//            631 => "USTANOVKA",
//            632 => "TIP_ZAGRUZKI",
//            633 => "MAKSIMALNAYA_ZAGRUZKA_BELYA",
//            634 => "SUSHKA",
//            635 => "UPRAVLENIE_3",
//            636 => "DISPLEY_3",
//            637 => "GABARITY_SHXGXV",
//            638 => "VES",
//            639 => "TSVET",
//            640 => "KLASS_ENERGOPOTREBLENIYA_1",
//            641 => "KLASS_EFFEKTIVNOSTI_STIRKI",
//            642 => "KLASS_EFFEKTIVNOSTI_OTZHIMA",
//            643 => "POTREBLYAEMAYA_ENERGIYA",
//            644 => "RASKHOD_VODY_ZA_STIRKU",
//            645 => "SKOROST_VRASHCHENIYA_PRI_OTZHIME",
//            646 => "VYBOR_SKOROSTI_OTZHIMA",
//            647 => "OTMENA_OTZHIMA",
//            648 => "ZASHCHITA_OT_PROTECHEK_VODY",
//            649 => "ZASHCHITA_OT_DETEY_1",
//            650 => "KONTROL_DISBALANSA",
//            651 => "KONTROL_ZA_UROVNEM_PENY",
//            652 => "KOLICHESTVO_PROGRAMM",
//            653 => "PROGRAMMA_STIRKI_SHERSTI",
//            654 => "SPETSIALNYE_PROGRAMMY",
//            655 => "TAYMER_OTSROCHKI_NACHALA_STIRKI",
//            656 => "OTSEK_DLYA_ZHIDKOGO_POROSHKA",
//            657 => "MATERIAL_BAKA",
//            658 => "ZAGRUZOCHNYY_LYUK",
//            659 => "UROVEN_SHUMA_STIRKA_OTZHIM",
//            660 => "DOPOLNITELNYE_VOZMOZHNOSTI_3",
//            661 => "DOPOLNITELNAYA_INFORMATSIYA_1",
//            662 => "TIP_9",
//            663 => "TERMOSTAT",
//            664 => "NAZNACHENIE_3",
//            665 => "ZAPORNYY_KLAPAN",
//            666 => "POKRYTIE",
//            667 => "FORMA_IZLIVA",
//            668 => "KONSTRUKTSIYA_3",
//            669 => "VSTRAIVAEMYY",
//            670 => "SPOSOB_MONTAZHA",
//            671 => "KOLICHESTVO_MONTAZHNYKH_OTVERSTIY",
//            672 => "LEYKA",
//            673 => "AERATOR",
//            674 => "IZLIV",
//            675 => "TIP_10",
//            676 => "MATERIAL_2",
//            677 => "FORMA",
//            678 => "OBEM_2",
//            679 => "UGLOVAYA_KONSTRUKTSIYA",
//            680 => "KOLICHESTVO_CHELOVEK",
//            681 => "MODIFIKATSIYA",
//            682 => "GIDROMASSAZH",
//            683 => "AEROMASSAZH",
//            684 => "KOLICHESTVO_FORSUNOK_DLYA_GIDROMASSAZHA",
//            685 => "KOLICHESTVO_FORSUNOK_DLYA_AEROMASSAZHA",
//            686 => "TIP_UPRAVLENIYA_2",
//            687 => "PROTIVOSKOLZYASHCHEE_POKRYTIE",
//            688 => "TIP_11",
//            689 => "OGRAZHDENIE",
//            690 => "FORMA_1",
//            691 => "PODDON_V_KOMPLEKTE",
//            692 => "MATERIAL_PODDONA",
//            693 => "TIP_PODDONA",
//            694 => "VYSOTA_PODDONA",
//            695 => "MATERIAL_PEREDNIKH_STENOK",
//            696 => "TOLSHCHINA_PEREDNIKH_STENOK",
//            697 => "VARIANTY_ISPOLNENIYA_PEREDNIKH_STENOK",
//            698 => "KONSTRUKTSIYA_DVEREY",
//            699 => "KOLICHESTVO_STVOROK_DVERI",
//            700 => "MASSAZH",
//            701 => "DOPOLNITELNYE_FUNKTSII",
//            702 => "MULTIMEDIA_I_SVYAZ",
//            703 => "PANEL_UPRAVLENIYA",
//            704 => "DISPLEY_4",
//            705 => "PROTIVOSKOLZYASHCHEE_POKRYTIE_DNA",
//            706 => "KOMPLEKTATSIYA_5",
//            707 => "SIDENIE",
//            708 => "SMESITEL",
//            709 => "OSVESHCHENIE",
//            710 => "GABARITY_SHKHVKHD",
//            711 => "TIP_PEREDNEGO_STEKLA",
//            712 => "RAMA_ROST_VELOSIPEDISTA_SM",
//            713 => "MODEL_1",
//            714 => "VOZRAST",
//            715 => "VOZRAST_REBENKA",
//            716 => "TIP_12",
//            717 => "TIP_PRIVODA",
//            718 => "SKLADNOY",
//            719 => "MATERIAL_RAMY",
//            720 => "RAZMERY_RAMY",
//            721 => "AMORTIZATSIYA",
//            722 => "KONSTRUKTSIYA_VILKI",
//            723 => "KONSTRUKTSIYA_RULEVOY_KOLONKI",
//            724 => "DIAMETR_KOLES",
//            725 => "NAIMENOVANIE_POKRYSHEK",
//            726 => "MATERIAL_OBODA",
//            727 => "DVOYNOY_OBOD",
//            728 => "MATERIAL_BORTIROVOCHNOGO_SHNURA",
//            729 => "VOZMOZHNOST_KREPLENIYA_BOKOVYKH_KOLES",
//            730 => "BOKOVYE_KOLESA_V_KOMPLEKTE",
//            731 => "PEREDNIY_TORMOZ",
//            732 => "TIP_PEREDNEGO_TORMOZA",
//            733 => "ZADNIY_TORMOZ",
//            734 => "TIP_ZADNEGO_TORMOZA",
//            735 => "KOLICHESTVO_SKOROSTEY",
//            736 => "ZADNIY_PEREKLYUCHATEL",
//            737 => "MANETKI",
//            738 => "KONSTRUKTSIYA_MANETOK",
//            739 => "KONSTRUKTSIYA_KARETKI",
//            740 => "KASSETY",
//            741 => "KOLICHESTVO_ZVEZD_V_KASSETE",
//            742 => "KOLICHESTVO_ZVEZD_SISTEMY",
//            743 => "KONSTRUKTSIYA_PEDALEY",
//            744 => "KONSTRUKTSIYA_RULYA",
//            745 => "NASTROYKA_POLOZHENIYA_RULYA",
//            746 => "MATERIAL_RAMKI_SEDLA",
//            747 => "KOMFORT",
//            748 => "ZVONOK",
//            749 => "ZASHCHITA_TSEPI",
//            750 => "KOMPLEKTATSIYA_6",
//            751 => "PROIZVODITEL_ATTR_E",
//        ],
//        "PROPERTY_CODE_MOBILE"      => [],
//        "META_KEYWORDS"             => "-",
//        "META_DESCRIPTION"          => "-",
//        "BROWSER_TITLE"             => "-",
//        "SET_LAST_MODIFIED"         => "N",
//        "INCLUDE_SUBSECTIONS"       => "Y",
//        "BASKET_URL"                => Config::get('BASKET_PAGE'),
//        "ACTION_VARIABLE"           => "action",
//        "PRODUCT_ID_VARIABLE"       => "id",
//        "SECTION_ID_VARIABLE"       => "SECTION_ID",
//        "PRODUCT_QUANTITY_VARIABLE" => "quantity",
//        "PRODUCT_PROPS_VARIABLE"    => "prop",
//        "FILTER_NAME"               => "arBlogProductsFilter",
//        "CACHE_FILTER"              => "Y",
//        "CACHE_GROUPS"              => "Y",
//        "CACHE_TIME"                => "36000000",
//        "CACHE_TYPE"                => "A",
//        "SET_TITLE"                 => "N",
//        "MESSAGE_404"               => "",
//        "SET_STATUS_404"            => "Y",
//        'SHOW_ALL_WO_SECTION' => 'Y',
//        "SHOW_404"                  => "N",
//        "DISPLAY_COMPARE"           => "Y",
//        "PAGE_ELEMENT_COUNT"        => 12,
//        "LINE_ELEMENT_COUNT"        => 4,
//        "PRICE_CODE"                => \SotbitOrigami::GetComponentPrices(["OPT","SMALL_OPT","BASE"]),
//        "USE_PRICE_COUNT"           => "N",
//        "SHOW_PRICE_COUNT"          => "1",
//
//        "PRICE_VAT_INCLUDE"          => "Y",
//        "USE_PRODUCT_QUANTITY"       => "Y",
//        "ADD_PROPERTIES_TO_BASKET"   => "Y",
//        "PARTIAL_PRODUCT_PROPERTIES" => "N",
//        "PRODUCT_PROPERTIES"         => [
//        ],
//
//        "DISPLAY_TOP_PAGER"               => "N",
//        "DISPLAY_BOTTOM_PAGER"            => "N",
//        "PAGER_TITLE"                     => "Товары",
//        "PAGER_SHOW_ALWAYS"               => "",
//        "PAGER_TEMPLATE"                  => "",
//        "PAGER_DESC_NUMBERING"            => "N",
//        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
//        "PAGER_SHOW_ALL"                  => "N",
//        "PAGER_BASE_LINK_ENABLE"          => "N",
//        "PAGER_BASE_LINK"                 => "N",
//        "PAGER_PARAMS_NAME"               => "N",
//        "LAZY_LOAD"                       => "N",
//        "MESS_BTN_LAZY_LOAD"              => "N",
//        "LOAD_ON_SCROLL"                  => "N",
//
//        "OFFERS_CART_PROPERTIES" => [
//            0 => "SIZES_SHOES",
//            1 => "SIZES_CLOTHES",
//            2 => "COLOR_REF",
//        ],
//        "OFFERS_FIELD_CODE"      => [
//            0 => "NAME",
//            1 => "PREVIEW_PICTURE",
//            2 => "DETAIL_PICTURE",
//            3 => "",
//        ],
//        "OFFERS_PROPERTY_CODE"   => [
//            1  => "CML2_BAR_CODE",
//            2  => "CML2_ARTICLE",
//            3  => "CML2_BASE_UNIT",
//            4  => "MORE_PHOTO",
//            5  => "FILES",
//            6  => "CML2_MANUFACTURER",
//            7 => "PROTSESSOR",
//            8 => "CHASTOTA_PROTSESSORA",
//            9 => "KOLICHESTVO_YADER_PROTSESORA",
//            10 => "OBEM_OPERATICHNOY_PAMYATI",
//            11 => "TIP_VIDEOKARTY",
//            12 => "OBEM_VIDEOPAMYATI",
//            13 => "USTANOVLENNAYA_OS",
//            14 => "OBEM_PAMYATI",
//            15 => "RAZMER",
//            16 => "TSVET",
//            17 => "TSVET_1",
//            18 => "VIDEOKARTA",
//        ],
//        "OFFERS_SORT_FIELD"      => "sort",
//        "OFFERS_SORT_ORDER"      => "id",
//        "OFFERS_SORT_FIELD2"     => "desc",
//        "OFFERS_SORT_ORDER2"     => "desc",
//        "OFFERS_LIMIT"           => 0,
//        'OFFER_TREE_PROPS' => array(
//            "PROTSESSOR",
//            "OBEM_OPERATICHNOY_PAMYATI",
//            "OBEM_PAMYATI",
//            "RAZMER",
//            "CHASTOTA_PROTSESSORA",
//            "TIP_VIDEOKARTY",
//            "TSVET",
//            "KOLICHESTVO_YADER_PROTSESORA",
//            "OBEM_VIDEOPAMYATI",
//            "TSVET_1",
//            "USTANOVLENNAYA_OS",
//            "CML2_MANUFACTURER",
//        ),
//        "SECTION_URL"               => SITE_DIR.'catalog/#SECTION_CODE_PATH#/',
//        "DETAIL_URL"                => SITE_DIR.'catalog/#SECTION_CODE_PATH#/#ELEMENT_CODE#/',
//        "USE_MAIN_ELEMENT_SECTION"  => "N",
//        'CONVERT_CURRENCY'          => "N",
//        'HIDE_NOT_AVAILABLE'        => "N",
//        'HIDE_NOT_AVAILABLE_OFFERS' => "N",
//
//        'LABEL_PROP'                  => [
//            0 => 'KHIT',
//            1 => 'NOVINKA'
//        ],
//        'LABEL_PROP_MOBILE'           => [],
//        'ADD_PICT_PROP'               => "MORE_PHOTO",
//        'PRODUCT_DISPLAY_MODE'        => "Y",
//        'OFFER_ADD_PICT_PROP'         => "MORE_PHOTO",
//        'PRODUCT_SUBSCRIPTION'        => "Y",
//        'SHOW_DISCOUNT_PERCENT'       => "Y",
//        'SHOW_OLD_PRICE'              => "Y",
//        'SHOW_MAX_QUANTITY'           => "Y",
//        "MESS_BTN_ADD_TO_BASKET"      => "В корзину",
//        "MESS_BTN_BUY"                => "Купить",
//        "MESS_BTN_COMPARE"            => "Сравнение",
//        "MESS_BTN_DETAIL"             => "Подробнее",
//        "MESS_BTN_SUBSCRIBE"          => "Подписаться",
//        "MESS_NOT_AVAILABLE"          => "Нет в наличии",
//        "MESS_RELATIVE_QUANTITY_MANY" => "Много",
//        "MESS_RELATIVE_QUANTITY_FEW"  => "Мало",
//        "MESS_RELATIVE_QUANTITY_NO"   => "Нет на складе",
//        'USE_VOTE_RATING'             => "Y",
//        'TEMPLATE_THEME'              => "",
//        "ADD_SECTIONS_CHAIN"          => "N",
//        'ADD_TO_BASKET_ACTION'        => "ADD",
//        'COMPARE_PATH'                => Config::get('COMPARE_PAGE'),
//        'COMPARE_NAME'                => "CATALOG_COMPARE_LIST",
//        'USE_COMPARE_LIST'            => 'Y',
//        'ACTION_PRODUCTS' => array("ADMIN"),
//        'VARIANT_LIST_VIEW' => 'ADMIN',
//        'SHOW_SLIDER' => "N",
//        'SECTION_NAME' => Loc::getMessage('SECT_BLOG_BLOCK_NAME')
//    ],
//    false
//);
?>

<?php

$this->SetViewTarget('blog_tags');
$arResult['TAGS'] = [];
$rs = \Bitrix\Iblock\ElementTable::getList([
    'filter' => [
        'ACTIVE' => 'Y',
        'IBLOCK_ID' => $arParams['IBLOCK_ID'],
    ],
    'select' => ['TAGS']
]);
while($el = $rs->fetch())
{
    if($el['TAGS'])
    {
        $tags = explode(',',$el['TAGS']);
        $arResult['TAGS'] = array_merge($arResult['TAGS'],$tags);
    }
}
$arResult['TAGS'] = array_unique($arResult['TAGS']);

if($arResult['TAGS'])
{
    ?>
    <div class="tags_wrapper">
        <div class="tags">
            <div class="tags__title">
                <?=\Bitrix\Main\Localization\Loc::getMessage('TAGS_TITLE')?>
            </div>
            <?
            foreach($arResult['TAGS'] as $tag)
            {
                ?>
                <a class="tag"
                   href="<?=$arResult['FOLDER']?>?blog_ff%5BTAGS%5D=<?=$tag?>&set_filter=Фильтр&set_filter=Y">
                    <?=$tag?>
                </a>
                <?
            }
            ?>
        </div>
    </div>
    <?
}
$this->EndViewTarget();
$this->SetViewTarget('blog_detail');
?>
<div class="detail_blog__banner">
    <?
    global $bannerFilter;
    $bannerFilter = [
        'ACTIVE' => 'Y',
        'PROPERTY_BANNER_TYPE' => Config::getBanner(['INNER']),

        array(
            "LOGIC" => "OR",
            array("PROPERTY_SHOW_SECTIONS" => $APPLICATION->GetCurPage(false)),
            array("PROPERTY_SHOW_SECTIONS" => false)
        ),
    ];
    $useRegion = (Config::get('USE_REGIONS') == 'Y') ? true : false;
    if ($useRegion && $_SESSION['SOTBIT_REGIONS']['ID']) {
        $bannerFilter['PROPERTY_REGIONS'] = [
            false,
            $_SESSION['SOTBIT_REGIONS']['ID']
        ];
    }
    $APPLICATION->IncludeComponent(
        "bitrix:news.list",
        "origami_inner_banner",
        [
            "IBLOCK_TYPE"                     => Config::get('IBLOCK_TYPE_BANNERS'),
            "IBLOCK_ID"                       => Config::get('IBLOCK_ID_BANNERS'),
            "NEWS_COUNT"                      => 3,
            "SORT_BY1"                        => 'sort',
            "SORT_ORDER1"                     => 'desc',
            "SORT_BY2"                        => 'id',
            "SORT_ORDER2"                     => 'asc',
            "FIELD_CODE"                      => [
                'PREVIEW_PICTURE',
                'DETAIL_PICTURE',
            ],
            "PROPERTY_CODE"                   => [
                'BUTTON_TEXT',
                'URL',
                'NEW_TAB',
            ],
            "DETAIL_URL"                      => $arResult["FOLDER"]
                .$arResult["URL_TEMPLATES"]["detail"],
            "SECTION_URL"                     => $arResult["FOLDER"]
                .$arResult["URL_TEMPLATES"]["section"],
            "IBLOCK_URL"                      => $arResult["FOLDER"]
                .$arResult["URL_TEMPLATES"]["news"],
            "DISPLAY_PANEL"                   => $arParams["DISPLAY_PANEL"],
            "SET_TITLE"                       => 'N',
            "SET_LAST_MODIFIED"               => $arParams["SET_LAST_MODIFIED"],
            "MESSAGE_404"                     => $arParams["MESSAGE_404"],
            "SET_STATUS_404"                  => $arParams["SET_STATUS_404"],
            "SHOW_404"                        => $arParams["SHOW_404"],
            "FILE_404"                        => $arParams["FILE_404"],
            "INCLUDE_IBLOCK_INTO_CHAIN"       => 'N',
            "CACHE_TYPE"                      => $arParams["CACHE_TYPE"],
            "CACHE_TIME"                      => $arParams["CACHE_TIME"],
            "CACHE_FILTER"                    => $arParams["CACHE_FILTER"],
            "CACHE_GROUPS"                    => $arParams["CACHE_GROUPS"],
            "DISPLAY_TOP_PAGER"               => $arParams["DISPLAY_TOP_PAGER"],
            "DISPLAY_BOTTOM_PAGER"            => $arParams["DISPLAY_BOTTOM_PAGER"],
            "PAGER_TITLE"                     => $arParams["PAGER_TITLE"],
            "PAGER_TEMPLATE"                  => $arParams["PAGER_TEMPLATE"],
            "PAGER_SHOW_ALWAYS"               => $arParams["PAGER_SHOW_ALWAYS"],
            "PAGER_DESC_NUMBERING"            => $arParams["PAGER_DESC_NUMBERING"],
            "PAGER_DESC_NUMBERING_CACHE_TIME" => $arParams["PAGER_DESC_NUMBERING_CACHE_TIME"],
            "PAGER_SHOW_ALL"                  => $arParams["PAGER_SHOW_ALL"],
            "PAGER_BASE_LINK_ENABLE"          => $arParams["PAGER_BASE_LINK_ENABLE"],
            "PAGER_BASE_LINK"                 => $arParams["PAGER_BASE_LINK"],
            "PAGER_PARAMS_NAME"               => $arParams["PAGER_PARAMS_NAME"],
            "DISPLAY_DATE"                    => $arParams["DISPLAY_DATE"],
            "DISPLAY_NAME"                    => "Y",
            "DISPLAY_PICTURE"                 => $arParams["DISPLAY_PICTURE"],
            "DISPLAY_PREVIEW_TEXT"            => $arParams["DISPLAY_PREVIEW_TEXT"],
            "PREVIEW_TRUNCATE_LEN"            => $arParams["PREVIEW_TRUNCATE_LEN"],
            "ACTIVE_DATE_FORMAT"              => $arParams["LIST_ACTIVE_DATE_FORMAT"],
            "USE_PERMISSIONS"                 => $arParams["USE_PERMISSIONS"],
            "GROUP_PERMISSIONS"               => $arParams["GROUP_PERMISSIONS"],
            "FILTER_NAME"                     => 'bannerFilter',
            "HIDE_LINK_WHEN_NO_DETAIL"        => $arParams["HIDE_LINK_WHEN_NO_DETAIL"],
            "CHECK_DATES"                     => $arParams["CHECK_DATES"],
        ],
        false
    );
    ?>
</div>

<div class="block_main_left__feedback">
    <p class="block_main_left__feedback_title fonts__main_text">
        <? $APPLICATION->IncludeComponent(
            "bitrix:main.include",
            "",
            [
                "AREA_FILE_SHOW" => "file",
                "PATH"           => SITE_DIR
                    ."include/sotbit_origami/subscribe_title.php",
            ]
        ); ?>
    </p>
    <? $APPLICATION->IncludeComponent(
	"bitrix:sender.subscribe", 
	"origami_sender_subscribe_section", 
	array(
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_TIME" => "3600",
		"CACHE_TYPE" => "A",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"CONFIRMATION" => "Y",
		"HIDE_MAILINGS" => "N",
		"SET_TITLE" => "N",
		"SHOW_HIDDEN" => "N",
		"USER_CONSENT" => "N",
		"USER_CONSENT_ID" => "0",
		"USER_CONSENT_IS_CHECKED" => "Y",
		"USER_CONSENT_IS_LOADED" => "N",
		"USE_PERSONALIZATION" => "Y",
		"COMPONENT_TEMPLATE" => "origami_sender_subscribe_section"
	),
	false
); ?>
</div>
<?
$this->EndViewTarget();
?>
